cloudformation:
  links:
    - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codebuild-project.html
  good:
    - |-
      Resources:
        GoodProject:
          Type: AWS::CodeBuild::Project
          Properties:
            Artifacts:
              EncryptionDisabled: false
            SecondaryArtifacts:
              - EncryptionDisabled: false
  bad:
    - |-
      Resources:
        GoodProject:
          Type: AWS::CodeBuild::Project
          Properties:
            Artifacts:
              EncryptionDisabled: true
            SecondaryArtifacts:
              - EncryptionDisabled: false
    - |-
      Resources:
        GoodProject:
          Type: AWS::CodeBuild::Project
          Properties:
            Artifacts:
              EncryptionDisabled: false
            SecondaryArtifacts:
              - EncryptionDisabled: true
terraform:
  links:
    - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/codebuild_project#encryption_disabled
  good:
    - |-
      resource "aws_codebuild_project" "good_example" {
        artifacts {}
      }
    - |-
      resource "aws_codebuild_project" "good_example" {
        artifacts {
          encryption_disabled = false
        }
      }
    - |-
      resource "aws_codebuild_project" "codebuild" {
        secondary_artifacts {
          encryption_disabled = false
        }
      }
  bad:
    - |-
      resource "aws_codebuild_project" "bad_example" {
        artifacts {
          encryption_disabled = true
        }
      }
    - |-
      resource "aws_codebuild_project" "bad_example" {
        artifacts {}

        secondary_artifacts {
          encryption_disabled = true
        }
      }
