dockerfile:
  good:
    - |-
      FROM ubuntu:18.04
      RUN apt-get update && apt-get install -y --no-install-recommends mysql-client     && rm -rf /var/lib/apt/lists/* && apt-get clean
      USER mike
      ENTRYPOINT mysql
    - |-
      FROM debian:trixie
      RUN <<EOF
      apt-get update
      apt-get install --no-install-recommends -y gettext
      EOF
  bad:
    - |-
      FROM ubuntu:18.04
      RUN apt-get update
      RUN apt-get install -y --no-install-recommends mysql-client     && rm -rf /var/lib/apt/lists/* && apt-get clean
      USER mike
      ENTRYPOINT mysql
