cloudformation:
  good:
    - |
      Resources:
        GoodExample:
          Properties:
            PubliclyAccessible: false
          Type: AWS::RDS::DBInstance
  bad:
    - |
      Resources:
        BadExample:
          Properties:
            PubliclyAccessible: true
          Type: AWS::RDS::DBInstance
terraform:
  good:
    - |-
      resource "aws_db_instance" "good_example" {
        publicly_accessible = false
      }
  bad:
    - |-
      resource "aws_db_instance" "bad_example" {
        publicly_accessible = true
      }
