terraform:
  good:
    - |-
      resource "aws_db_instance" "good_example" {
        storage_encrypted = true
      }
  bad:
    - |-
      resource "aws_db_instance" "bad_example" {

      }
cloudformation:
  good:
    - |-
      Resources:
          GoodExample:
              Properties:
                  KmsKeyId: something
                  StorageEncrypted: true
              Type: AWS::RDS::DBInstance
  bad:
    - |-
      Resources:
          BadExample:
              Properties:
                  StorageEncrypted: false
              Type: AWS::RDS::DBInstance
