terraform:
  good:
    - |-
      resource "aws_security_group" "good_example" {
        # ...
      }
  bad:
    - |-
      resource "aws_db_security_group" "bad_example" {
        # ...
      }
cloudformation:
  good:
    - |-
      AWSTemplateFormatVersion: 2010-09-09T00:00:00Z
      Description: Good example of rds sgr
      Resources: null
  bad:
    - |-
      AWSTemplateFormatVersion: 2010-09-09T00:00:00Z
      Description: Bad example of rds sgr
      Resources:
          Queue:
              Properties:
                  Description: ""
              Type: AWS::RDS::DBSecurityGroup
