cloudformation:
  good:
    - |-
      Resources:
        GoodExample:
          Type: AWS::RDS::DBInstance
          Properties:
            EnablePerformanceInsights: true
            PerformanceInsightsKMSKeyId: something
  bad:
    - |-
      Resources:
        BadExample:
          Type: AWS::RDS::DBInstance
          Properties:
            EnablePerformanceInsights: true
terraform:
  good:
    - |-
      resource "aws_rds_cluster_instance" "good_example" {
        name                            = "bar"
        performance_insights_enabled    = true
        performance_insights_kms_key_id = "arn:aws:kms:us-west-2:111122223333:key/1234abcd-12ab-34cd-56ef-1234567890ab"
      }
  bad:
    - |-
      resource "aws_rds_cluster_instance" "bad_example" {
        name                            = "bar"
        performance_insights_enabled    = true
        performance_insights_kms_key_id = ""
      }
