terraform:
  good:
    - "resource \"aws_rds_cluster_instance\" \"good_example\" {\n  name                            = \"bar\"\n  performance_insights_enabled    = true\n  performance_insights_kms_key_id = \"arn:aws:kms:us-west-2:111122223333:key/1234abcd-12ab-34cd-56ef-1234567890ab\"\n}\n  "
  bad:
    - "resource \"aws_rds_cluster_instance\" \"bad_example\" {\n  name                            = \"bar\"\n  performance_insights_enabled    = true\n  performance_insights_kms_key_id = \"\"\n}\n  "
cloudformation:
  good:
    - |
      Resources:
          GoodExample:
              Properties:
                  EnablePerformanceInsights: true
                  PerformanceInsightsKMSKeyId: something
              Type: AWS::RDS::DBInstance
  bad:
    - |
      Resources:
          BadExample:
              Properties:
                  EnablePerformanceInsights: true
              Type: AWS::RDS::DBInstance
