cloudformation:
  good:
    - |-
      AWSTemplateFormatVersion: "2010-09-09"

      Description: Good example of queue policy

      Resources:
        MyQueue:
          Type: AWS::SQS::Queue
          Properties:
            Name: something

        SampleSQSPolicy:
          Type: AWS::SQS::QueuePolicy
          Properties:
            PolicyDocument:
              Statement:
                - Action:
                    - SQS:SendMessage
                    - SQS:ReceiveMessage
                  Effect: Allow
                  Principal:
                    AWS:
                      - "111122223333"
                  Resource: arn:aws:sqs:us-east-2:444455556666:queue2
            Queues:
              - !Ref MyQueue
  bad:
    - |-
      AWSTemplateFormatVersion: "2010-09-09"

      Description: Bad example of queue policy

      Resources:
        MyQueue:
          Type: AWS::SQS::Queue
          Properties:
            Name: something

        SampleSQSPolicy:
          Type: AWS::SQS::QueuePolicy
          Properties:
            PolicyDocument:
              Statement:
                - Action:
                    - '*'
                  Effect: Allow
                  Principal:
                    AWS:
                      - "111122223333"
                  Resource: arn:aws:sqs:us-east-2:444455556666:queue2
            Queues:
              - !Ref MyQueue
terraform:
  good:
    - |-
      resource "aws_sqs_queue_policy" "good_example" {
        queue_url = aws_sqs_queue.q.id

        policy = <<POLICY
       {
         "Statement": [
           {
             "Effect": "Allow",
             "Principal": "*",
             "Action": "sqs:SendMessage"
           }
         ]
       }
       POLICY
      }
  bad:
    - |-
      resource "aws_sqs_queue_policy" "bad_example" {
        queue_url = aws_sqs_queue.q.id

        policy = <<POLICY
       {
         "Statement": [
           {
             "Effect": "Allow",
             "Principal": "*",
             "Action": "*"
           }
         ]
       }
       POLICY
      }
