terraform:
  good:
    - |-
      resource "aws_sqs_queue" "good_example" {
        kms_master_key_id = "/blah"
      }
  bad:
    - |-
      resource "aws_sqs_queue" "bad_example" {
        kms_master_key_id = "alias/aws/sqs"
      }
cloudformation:
  good:
    - |-
      AWSTemplateFormatVersion: 2010-09-09T00:00:00Z
      Description: Good example of queue
      Resources:
          Queue:
              Properties:
                  KmsMasterKeyId: some-key
                  QueueName: my-queue
              Type: AWS::SQS::Queue
  bad:
    - |-
      AWSTemplateFormatVersion: 2010-09-09T00:00:00Z
      Description: Bad example of queue
      Resources:
          Queue:
              Properties:
                  KmsMasterKeyId: alias/aws/sqs
                  QueueName: my-queue
              Type: AWS::SQS::Queue
