terraform:
  good:
    - "resource \"openstack_networking_secgroup_rule_v2\" \"rule_1\" {\n  direction        = \"ingress\"\n  ethertype        = \"IPv4\"\n  protocol         = \"tcp\"\n  port_range_min   = 22\n  port_range_max   = 22\n  remote_ip_prefix = \"1.2.3.4/32\"\n}\n    "
  bad:
    - "resource \"openstack_networking_secgroup_rule_v2\" \"rule_1\" {\n  direction        = \"ingress\"\n  ethertype        = \"IPv4\"\n  protocol         = \"tcp\"\n  port_range_min   = 22\n  port_range_max   = 22\n  remote_ip_prefix = \"0.0.0.0/0\"\n}\n    "
