cloudformation:
  good:
    - |-
      Resources:
        GoodExample:
          Type: AWS::ECS::TaskDefinition
          Properties:
            ContainerDefinitions:
              - Image: amazon/amazon-ecs-sample
            Volumes:
              - EFSVolumeConfiguration:
                  FilesystemId: fs1
                  TransitEncryption: ENABLED
                Name: jenkins-home
  bad:
    - |-
      Resources:
        BadExample:
          Type: AWS::ECS::TaskDefinition
          Properties:
            ContainerDefinitions:
              - Image: amazon/amazon-ecs-sample
            Volumes:
              - EFSVolumeConfiguration:
                  FilesystemId: fs1
                  TransitEncryption: DISABLED
                Name: jenkins-home
terraform:
  links:
    - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_task_definition#transit_encryption
  good:
    - |-
      resource "aws_ecs_task_definition" "good_example" {
        container_definitions = file("task-definitions/service.json")
        volume {
          name = "service-storage"
          efs_volume_configuration {
            file_system_id     = aws_efs_file_system.fs.id
            transit_encryption = "ENABLED"
          }
        }
      }
  bad:
    - |-
      resource "aws_ecs_task_definition" "bad_example" {
        container_definitions = file("task-definitions/service.json")
        volume {
          name = "service-storage"
          efs_volume_configuration {
            file_system_id = aws_efs_file_system.fs.id
            root_directory = "/opt/data"
          }
        }
      }
