terraform:
  good:
    - |-
      resource "aws_ecs_cluster" "good_example" {
        name = "services-cluster"

        setting {
          name  = "containerInsights"
          value = "enabled"
        }
      }
  bad:
    - |-
      resource "aws_ecs_cluster" "bad_example" {
        name = "services-cluster"
      }
cloudformation:
  good:
    - |-
      Resources:
          GoodExample:
              Properties:
                  ClusterName: MyCluster
                  ClusterSettings:
                      - Name: containerInsights
                        Value: enabled
              Type: AWS::ECS::Cluster
  bad:
    - |-
      Resources:
          BadExample:
              Properties:
                  ClusterName: MyCluster
              Type: AWS::ECS::Cluster
