cloudformation:
  good:
    - |-
      Resources:
        GoodExample:
          Type: AWS::ECS::Cluster
          Properties:
            ClusterName: MyCluster
            ClusterSettings:
              - Name: containerInsights
                Value: enabled

        GoodTask:
          Type: AWS::ECS::TaskDefinition
          Properties:
            ContainerDefinitions:
              - Image: cfsec/cfsec:latest
                LogConfiguration:
                  LogDriver: awslogs
                  Options:
                    awslogs-group: cfsec-logs
                    awslogs-region: !Ref AWS::Region
                    awslogs-stream-prefix: cfsec
                MountPoints:
                  - ContainerPath: /src
                    SourceVolume: src
                Name: cfsec
            Cpu: 512
            Family: CFSec scan
            Memory: 1024
            NetworkMode: awsvpc
            RequiresCompatibilities:
              - FARGATE
              - EC2
            Volumes:
              - EFSVolumeConfiguration:
                  FilesystemId: fs1
                  TransitEncryption: ENABLED
                Name: jenkins-home
  bad:
    - |-
      Resources:
        BadExample:
          Type: AWS::ECS::Cluster
          Properties:
            ClusterName: MyCluster
            ClusterSettings:
              - Name: containerInsights
                Value: enabled

        BadTask:
          Type: AWS::ECS::TaskDefinition
          Properties:
            ContainerDefinitions:
              - Environment:
                  - Name: AWS_ACCESS_KEY_ID
                    Value: AIPA8YOHGIS58IBFDU3E
                Image: cfsec/cfsec:latest
                LogConfiguration:
                  LogDriver: awslogs
                  Options:
                    awslogs-group: cfsec-logs
                    awslogs-region: !Ref AWS::Region
                    awslogs-stream-prefix: cfsec
                MountPoints:
                  - ContainerPath: /src
                    SourceVolume: src
                Name: cfsec
            Cpu: 512
            Family: CFSec scan
            Memory: 1024
            NetworkMode: awsvpc
            RequiresCompatibilities:
              - FARGATE
              - EC2
            Volumes:
              - EFSVolumeConfiguration:
                  FilesystemId: fs1
                  TransitEncryption: DISABLED
                Name: jenkins-home
terraform:
  good:
    - |-
      resource "aws_ecs_task_definition" "good_example" {
        container_definitions = <<EOF
       [
         {
           "name": "my_service",
           "essential": true,
           "memory": 256,
           "environment": [
             { "name": "ENVIRONMENT", "value": "development" }
           ]
         }
       ]
       EOF

      }
  bad:
    - |-
      resource "aws_ecs_task_definition" "bad_example" {
        container_definitions = <<EOF
       [
         {
           "name": "my_service",
           "essential": true,
           "memory": 256,
           "environment": [
             { "name": "ENVIRONMENT", "value": "development" },
             { "name": "DATABASE_PASSWORD", "value": "oh no D:"}
           ]
         }
       ]
       EOF

      }
