cloudformation:
  good:
    - |-
      Resources:
        GoodExample:
          Type: AWS::ECS::TaskDefinition
          Properties:
            ContainerDefinitions:
              - Image: amazon/amazon-ecs-sample
  bad:
    - |-
      Resources:
        BadExample:
          Type: AWS::ECS::TaskDefinition
          Properties:
            ContainerDefinitions:
              - Environment:
                  - Name: AWS_ACCESS_KEY_ID
                    Value: AIPA8YOHGIS58IBFDU3E
                Image: amazon/amazon-ecs-sample
terraform:
  links:
    - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_task_definition
  good:
    - |-
      resource "aws_ecs_task_definition" "good_example" {
        container_definitions = <<EOF
       [
         {
           "name": "my_service",
           "environment": [
             { "name": "ENVIRONMENT", "value": "development" }
           ]
         }
       ]
       EOF
      }
  bad:
    - |-
      resource "aws_ecs_task_definition" "bad_example" {
        container_definitions = <<EOF
       [
         {
           "name": "my_service",
           "environment": [
             { "name": "ENVIRONMENT", "value": "development" },
             { "name": "DATABASE_PASSWORD", "value": "oh no D:"}
           ]
         }
       ]
       EOF
      }
