cloudformation:
  good:
    - |-
      Resources:
        GoodExampleCacheGroup:
          Type: AWS::ElastiCache::SecurityGroup
          Properties:
            Description: Some description

        GoodExampleEc2SecurityGroup:
          Type: AWS::EC2::SecurityGroup
          Properties:
            GroupDescription: Good Elasticache Security Group
            GroupName: GoodExample

        GoodSecurityGroupIngress:
          Type: AWS::ElastiCache::SecurityGroupIngress
          Properties:
            CacheSecurityGroupName: GoodExampleCacheGroup
            EC2SecurityGroupName: GoodExampleEc2SecurityGroup
  bad:
    - |-
      Resources:
        BadExampleCacheGroup:
          Type: AWS::ElastiCache::SecurityGroup
          Properties:
            Tags:
              - Name: BadExample

        BadExampleEc2SecurityGroup:
          Type: AWS::EC2::SecurityGroup
          Properties:
            GroupDescription: Bad Elasticache Security Group
            GroupName: BadExample

        BadSecurityGroupIngress:
          Type: AWS::ElastiCache::SecurityGroupIngress
          Properties:
            CacheSecurityGroupName: BadExampleCacheGroup
            EC2SecurityGroupName: BadExampleEc2SecurityGroup
terraform:
  good:
    - |-
      resource "aws_security_group" "bar" {
        name = "security-group"
      }

      resource "aws_elasticache_security_group" "good_example" {
        name                 = "elasticache-security-group"
        security_group_names = [aws_security_group.bar.name]
        description          = "something"
      }
  bad:
    - |-
      resource "aws_security_group" "bar" {
        name = "security-group"
      }

      resource "aws_elasticache_security_group" "bad_example" {
        name                 = "elasticache-security-group"
        security_group_names = [aws_security_group.bar.name]
        description          = ""
      }
