cloudformation:
  links:
    - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticache-replicationgroup.html
  good:
    - |-
      Resources:
        GoodExample:
          Type: AWS::ElastiCache::ReplicationGroup
          Properties:
            AtRestEncryptionEnabled: true
  bad:
    - |-
      Resources:
        BadExample:
          Type: AWS::ElastiCache::ReplicationGroup
          Properties:
            AtRestEncryptionEnabled: false
terraform:
  links:
    - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_replication_group#at_rest_encryption_enabled
  good:
    - |-
      resource "aws_elasticache_replication_group" "good_example" {
        replication_group_id          = "foo"
        replication_group_description = "my foo cluster"

        at_rest_encryption_enabled = true
      }
  bad:
    - |-
      resource "aws_elasticache_replication_group" "bad_example" {
        replication_group_id          = "foo"
        replication_group_description = "my foo cluster"

        at_rest_encryption_enabled = false
      }
