cloudformation:
  good:
    - |-
      Resources:
        GoodExample:
          Type: AWS::ElastiCache::ReplicationGroup
          Properties:
            TransitEncryptionEnabled: true
  bad:
    - |-
      Resources:
        BadExample:
          Type: AWS::ElastiCache::ReplicationGroup
terraform:
  links:
    - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_replication_group#transit_encryption_enabled
  good:
    - |-
      resource "aws_elasticache_replication_group" "good_example" {
        transit_encryption_enabled = true
      }
  bad:
    - |-
      resource "aws_elasticache_replication_group" "bad_example" {
        transit_encryption_enabled = false
      }
