cloudformation:
  good:
    - |-
      Resources:
        GoodExample:
          Type: AWS::ElastiCache::ReplicationGroup
          Properties:
            AutomaticFailoverEnabled: true
            CacheNodeType: cache.r3.large
            CacheSubnetGroupName: !Ref CacheSubnetGroup
            Engine: redis
            EngineVersion: "3.2"
            NumNodeGroups: "2"
            Port: 6379
            PreferredMaintenanceWindow: sun:05:00-sun:09:00
            ReplicasPerNodeGroup: "3"
            ReplicationGroupDescription: A sample replication group
            SecurityGroupIds:
              - !Ref ReplicationGroupSG
            SnapshotRetentionLimit: 5
            SnapshotWindow: 10:00-12:00
            TransitEncryptionEnabled: true
  bad:
    - |-
      Resources:
        BadExample:
          Type: AWS::ElastiCache::ReplicationGroup
          Properties:
            AutomaticFailoverEnabled: true
            CacheNodeType: cache.r3.large
            CacheSubnetGroupName: !Ref CacheSubnetGroup
            Engine: redis
            EngineVersion: "3.2"
            NumNodeGroups: "2"
            Port: 6379
            PreferredMaintenanceWindow: sun:05:00-sun:09:00
            ReplicasPerNodeGroup: "3"
            ReplicationGroupDescription: A sample replication group
            SecurityGroupIds:
              - !Ref ReplicationGroupSG
            SnapshotRetentionLimit: 5
            SnapshotWindow: 10:00-12:00
terraform:
  good:
    - |-
      resource "aws_elasticache_replication_group" "good_example" {
        replication_group_id          = "foo"
        replication_group_description = "my foo cluster"
        transit_encryption_enabled    = true
      }
  bad:
    - |-
      resource "aws_elasticache_replication_group" "bad_example" {
        replication_group_id          = "foo"
        replication_group_description = "my foo cluster"
        transit_encryption_enabled    = false
      }
