cloudformation:
  good:
    - |-
      Resources:
        GoodExample:
          Type: AWS::ElastiCache::CacheCluster
          Properties:
            CacheNodeType: cache.m3.medium
            Engine: redis
            SnapshotRetentionLimit: 7
    - |-
      Resources:
        GoodExample:
          Type: AWS::ElastiCache::CacheCluster
          Properties:
            Engine: redis
            CacheNodeType: cache.t1.micro
    - |-
      Resources:
        GoodExample:
          Type: AWS::ElastiCache::CacheCluster
          Properties:
            Engine: memcached
  bad:
    - |-
      Resources:
        BadExample:
          Type: AWS::ElastiCache::CacheCluster
          Properties:
            Engine: redis
            CacheNodeType: cache.m3.medium
terraform:
  links:
    - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_cluster#snapshot_retention_limit
  good:
    - |-
      resource "aws_elasticache_cluster" "good_example" {
        engine                   = "redis"
        node_type                = "cache.m4.large"
        snapshot_retention_limit = 5
      }
    - |-
      resource "aws_elasticache_cluster" "good_example" {
        engine    = "memcached"
        node_type = "cache.m4.large"
      }
    - |-
      resource "aws_elasticache_cluster" "good_example" {
        engine    = "redis"
        node_type = "cache.t1.micro"
      }
  bad:
    - |-
      resource "aws_elasticache_cluster" "bad_example" {
        engine    = "redis"
        node_type = "cache.m4.large"
      }
