cloudformation:
  good:
    - |
      AWSTemplateFormatVersion: "2010-09-09T00:00:00Z"
      Description: Good example of redshift sgr
      Resources: null
  bad:
    - |
      AWSTemplateFormatVersion: "2010-09-09T00:00:00Z"
      Description: Bad example of redshift sgr
      Resources:
        Queue:
          Properties:
            Description: ""
          Type: AWS::Redshift::ClusterSecurityGroup
