cloudformation:
  good:
    - |-
      AWSTemplateFormatVersion: "2010-09-09"

      Description: Good example of redshift sgr

      Resources: null
  bad:
    - |-
      AWSTemplateFormatVersion: "2010-09-09"

      Description: Bad example of redshift sgr

      Resources:
        Queue:
          Type: AWS::Redshift::ClusterSecurityGroup
          Properties:
            Description: ""
