cloudformation:
  good:
    - |-
      Resources:
        GoodCluster:
          Type: AWS::Redshift::Cluster
          Properties:
            ClusterSubnetGroupName: my-subnet-group
  bad:
    - |-
      Resources:
        BadCluster:
          Type: AWS::Redshift::Cluster
          Properties:
            DBName: mydb
terraform:
  links:
    - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshift_cluster#cluster_subnet_group_name
  good:
    - |-
      resource "aws_redshift_cluster" "good_example" {
        cluster_identifier        = "tf-redshift-cluster"
        database_name             = "mydb"
        cluster_subnet_group_name = "redshift_subnet"
      }
  bad:
    - |-
      resource "aws_redshift_cluster" "bad_example" {
        cluster_identifier = "tf-redshift-cluster"
        database_name      = "mydb"
      }
