terraform:
  good:
    - |-
      resource "google_container_cluster" "primary" {
        name     = "my-gke-cluster"
        location = "us-central1"

        remove_default_node_pool = true
        initial_node_count       = 1
      }

      resource "google_container_node_pool" "good_example" {
        cluster = google_container_cluster.primary.id
        node_config {
          workload_metadata_config {
            node_metadata = "SECURE"
          }
        }
      }
  bad:
    - |-
      resource "google_container_cluster" "primary" {
        name     = "my-gke-cluster"
        location = "us-central1"

        remove_default_node_pool = true
        initial_node_count       = 1
      }

      resource "google_container_node_pool" "bad_example" {
        cluster = google_container_cluster.primary.id
        node_config {
          workload_metadata_config {
            node_metadata = "EXPOSE"
          }
        }
      }
