terraform:
  good:
    - |-
      resource "nifcloud_db_security_group" "good_example" {
        rule {
          cidr_ip = "10.0.0.0/16"
        }
      }
  bad:
    - |-
      resource "nifcloud_db_security_group" "bad_example" {
        rule {
          cidr_ip = "0.0.0.0/0"
        }
      }
