---
node:
  apiserver:
    confs:
      - /etc/kubernetes/manifests/kube-apiserver.yaml
      - /etc/kubernetes/manifests/kube-apiserver.yml
      - /etc/kubernetes/manifests/kube-apiserver.manifest
      - /var/snap/kube-apiserver/current/args
      - /var/snap/microk8s/current/args/kube-apiserver
      - /etc/origin/master/master-config.yaml
      - /etc/kubernetes/manifests/talos-kube-apiserver.yaml
      - /var/lib/rancher/rke2/agent/pod-manifests/kube-apiserver.yaml
    defaultconf: /etc/kubernetes/manifests/kube-apiserver.yaml
  controllermanager:
    confs:
      - /etc/kubernetes/manifests/kube-controller-manager.yaml
      - /etc/kubernetes/manifests/kube-controller-manager.yml
      - /etc/kubernetes/manifests/kube-controller-manager.manifest
      - /var/snap/kube-controller-manager/current/args
      - /var/snap/microk8s/current/args/kube-controller-manager
      - /etc/kubernetes/manifests/talos-kube-controller-manager.yaml
      - /var/lib/rancher/rke2/agent/pod-manifests/kube-controller-manager.yaml
    defaultconf: /etc/kubernetes/manifests/kube-controller-manager.yaml
    kubeconfig:
      - /etc/kubernetes/controller-manager.conf
      - /var/lib/kube-controller-manager/kubeconfig
      - /system/secrets/kubernetes/kube-controller-manager/kubeconfig
    defaultkubeconfig: /etc/kubernetes/controller-manager.conf
  scheduler:
    confs:
      - /etc/kubernetes/manifests/kube-scheduler.yaml
      - /etc/kubernetes/manifests/kube-scheduler.yml
      - /etc/kubernetes/manifests/kube-scheduler.manifest
      - /var/snap/kube-scheduler/current/args
      - /var/snap/microk8s/current/args/kube-scheduler
      - /etc/origin/master/scheduler.json
      - /etc/kubernetes/manifests/talos-kube-scheduler.yaml
      - /var/lib/rancher/rke2/agent/pod-manifests/kube-scheduler.yaml
    defaultconf: /etc/kubernetes/manifests/kube-scheduler.yaml
    kubeconfig:
      - /etc/kubernetes/scheduler.conf
      - /var/lib/kube-scheduler/kubeconfig
      - /var/lib/kube-scheduler/config.yaml
      - /system/secrets/kubernetes/kube-scheduler/kubeconfig
    defaultkubeconfig: /etc/kubernetes/scheduler.conf
  etcd:
    datadirs:
      - /var/lib/etcd/default.etcd
      - /var/lib/etcd/data.etcd
    confs:
      - /etc/kubernetes/manifests/etcd.yaml
      - /etc/kubernetes/manifests/etcd.yml
      - /etc/kubernetes/manifests/etcd.manifest
      - /etc/etcd/etcd.conf
      - /var/snap/etcd/common/etcd.conf.yml
      - /var/snap/etcd/common/etcd.conf.yaml
      - /var/snap/microk8s/current/args/etcd
      - /usr/lib/systemd/system/etcd.service
      - /var/lib/rancher/rke2/agent/pod-manifests/etcd.yaml
      - /var/lib/rancher/k3s/server/db/etcd/config
    defaultconf: /etc/kubernetes/manifests/etcd.yaml
    defaultdatadir: /var/lib/etcd/default.etcd
  flanneld:
    defaultconf: /etc/sysconfig/flanneld
  kubernetes:
    defaultconf: /etc/kubernetes/config
  kubelet:
    cafile:
      - /etc/kubernetes/pki/ca.crt
      - /etc/kubernetes/certs/ca.crt
      - /etc/kubernetes/cert/ca.pem
      - /var/snap/microk8s/current/certs/ca.crt
      - /var/lib/rancher/rke2/agent/server.crt
      - /var/lib/rancher/rke2/agent/client-ca.crt
      - /var/lib/rancher/k3s/agent/client-ca.crt
      - /system/secrets/kubernetes/kube-apiserver/ca.crt
      - /system/secrets/kubernetes/kubelet/ca.crt
    svc:
      - /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
      - /etc/systemd/system/kubelet.service
      - /lib/systemd/system/kubelet.service
      - /etc/systemd/system/snap.kubelet.daemon.service
      - /etc/systemd/system/snap.microk8s.daemon-kubelet.service
      - /etc/systemd/system/atomic-openshift-node.service
      - /etc/systemd/system/origin-node.service
      - /system/services/kubelet.yaml
      - /etc/cri/conf.d/20-customization.part
    bins:
      - hyperkube kubelet
      - kubelet
    kubeconfig:
      - /etc/kubernetes/kubelet.conf
      - /etc/kubernetes/kubelet-kubeconfig.conf
      - /var/lib/kubelet/kubeconfig
      - /etc/kubernetes/kubelet-kubeconfig
      - /etc/kubernetes/kubelet/kubeconfig
      - /etc/kubernetes/ssl/kubecfg-kube-node.yaml
      - /var/snap/microk8s/current/credentials/kubelet.config
      - /etc/kubernetes/kubeconfig-kubelet
      - /var/lib/rancher/rke2/agent/kubelet.kubeconfig
      - /var/lib/rancher/k3s/server/cred/admin.kubeconfig
      - /var/lib/rancher/k3s/agent/kubelet.kubeconfig
      - /system/secrets/kubernetes/kubelet/kubeconfig
    confs:
      - /etc/kubernetes/kubelet-config.yaml
      - /var/lib/kubelet/config.yaml
      - /var/lib/kubelet/config.yml
      - /etc/kubernetes/kubelet/kubelet-config.json
      - /etc/kubernetes/kubelet/config
      - /home/kubernetes/kubelet-config.yaml
      - /home/kubernetes/kubelet-config.yml
      - /etc/default/kubeletconfig.json
      - /etc/default/kubelet
      - /var/lib/kubelet/kubeconfig
      - /var/snap/kubelet/current/args
      - /var/snap/microk8s/current/args/kubelet
      - /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
      - /etc/systemd/system/kubelet.service
      - /lib/systemd/system/kubelet.service
      - /etc/systemd/system/snap.kubelet.daemon.service
      - /etc/systemd/system/snap.microk8s.daemon-kubelet.service
      - /etc/kubernetes/kubelet.yaml
      - /var/lib/rancher/rke2/agent/kubelet.kubeconfig
      - /system/secrets/kubernetes/kubelet/config.yaml
      - /etc/cri/conf.d/20-customization.part
    defaultconf: /var/lib/kubelet/config.yaml
    defaultsvc: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    defaultkubeconfig: /etc/kubernetes/kubelet.conf
    defaultcafile: /etc/kubernetes/pki/ca.crt
  proxy:
    bins:
      - kube-proxy
      - hyperkube proxy
      - hyperkube kube-proxy
      - proxy
      - openshift start network
    confs:
      - /etc/kubernetes/proxy
      - /etc/kubernetes/addons/kube-proxy-daemonset.yaml
      - /etc/kubernetes/addons/kube-proxy-daemonset.yml
      - /var/snap/kube-proxy/current/args
      - /var/snap/microk8s/current/args/kube-proxy
    kubeconfig:
      - /etc/kubernetes/kubelet-kubeconfig
      - /etc/kubernetes/kubelet-kubeconfig.conf
      - /etc/kubernetes/kubelet/config
      - /etc/kubernetes/ssl/kubecfg-kube-proxy.yaml
      - /var/lib/kubelet/kubeconfig
      - /var/snap/microk8s/current/credentials/proxy.config
      - /var/lib/rancher/rke2/agent/kubeproxy.kubeconfig
      - /var/lib/rancher/k3s/agent/kubeproxy.kubeconfig
      - /system/secrets/kubernetes/kube-proxy/kubeconfig
    svc:
      - /lib/systemd/system/kube-proxy.service
      - /etc/systemd/system/snap.microk8s.daemon-proxy.service
      - /system/services/kube-proxy.yaml
    defaultconf: /etc/kubernetes/addons/kube-proxy-daemonset.yaml
    defaultkubeconfig: /etc/kubernetes/proxy.conf
