cloudformation:
  good:
    - |-
      Resources:
        GoodTopic:
          Type: AWS::SNS::Topic
          Properties:
            KmsMasterKeyId: some-key
            TopicName: blah
  bad:
    - |-
      Resources:
        BadTopic:
          Type: AWS::SNS::Topic
          Properties:
            TopicName: blah
terraform:
  links:
    - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sns_topic#example-with-server-side-encryption-sse
  good:
    - |-
      resource "aws_sns_topic" "good_example" {
        kms_master_key_id = "/blah"
      }
    - |-
      resource "aws_sns_topic" "good_example" {
        kms_master_key_id = "alias/aws/sns"
      }
  bad:
    - |-
      resource "aws_sns_topic" "bad_example" {}
