terraform:
  good:
    - |-
      resource "aws_sns_topic" "good_example" {
        kms_master_key_id = "/blah"
      }
  bad:
    - |-
      resource "aws_sns_topic" "bad_example" {
        # no key id specified
      }
cloudformation:
  good:
    - |
      Resources:
          GoodTopic:
              Properties:
                  KmsMasterKeyId: some-key
                  TopicName: blah
              Type: AWS::SQS::Topic
  bad:
    - |
      Resources:
          BadTopic:
              Properties:
                  TopicName: blah
              Type: AWS::SNS::Topic
