cloudformation:
  good:
    - |-
      Resources:
        GoodExample:
          Type: AWS::CloudTrail::Trail
          Properties:
            IsLogging: true
            IsMultiRegionTrail: true
            KmsKeyId: alias/CloudtrailKey
            S3BucketName: CloudtrailBucket
            S3KeyPrefix: /trailing
            TrailName: Cloudtrail
  bad:
    - |-
      Resources:
        BadExample:
          Type: AWS::CloudTrail::Trail
          Properties:
            IsLogging: true
            IsMultiRegionTrail: false
            S3BucketName: CloudtrailBucket
            S3KeyPrefix: /trailing
            TrailName: Cloudtrail
terraform:
  good:
    - |-
      resource "aws_cloudtrail" "good_example" {
        is_multi_region_trail      = true
        enable_log_file_validation = true
        kms_key_id                 = var.kms_id

        event_selector {
          read_write_type           = "All"
          include_management_events = true

          data_resource {
            type   = "AWS::S3::Object"
            values = ["${data.aws_s3_bucket.important-bucket.arn}/"]
          }
        }
      }
  bad:
    - |-
      resource "aws_cloudtrail" "bad_example" {
        is_multi_region_trail = true

        event_selector {
          read_write_type           = "All"
          include_management_events = true

          data_resource {
            type   = "AWS::S3::Object"
            values = ["${data.aws_s3_bucket.important-bucket.arn}/"]
          }
        }
      }
