cloudformation:
  links:
    - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudtrail-trail.html#cfn-cloudtrail-trail-kmskeyid
  good:
    - |-
      Resources:
        GoodExample:
          Type: AWS::CloudTrail::Trail
          Properties:
            IsLogging: true
            IsMultiRegionTrail: true
            KmsKeyId: alias/CloudtrailKey
            S3BucketName: CloudtrailBucket
            S3KeyPrefix: /trailing
            TrailName: Cloudtrail
  bad:
    - |-
      Resources:
        BadExample:
          Type: AWS::CloudTrail::Trail
          Properties:
            IsLogging: true
            IsMultiRegionTrail: false
            S3BucketName: CloudtrailBucket
            S3KeyPrefix: /trailing
            TrailName: Cloudtrail
terraform:
  links:
    - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudtrail#kms_key_id
  good:
    - |-
      resource "aws_kms_key" "trail" {
        enable_key_rotation = true
      }
      resource "aws_kms_alias" "trail" {
        name          = "alias/trail"
        target_key_id = aws_kms_key.trail.key_id
      }

      resource "aws_cloudtrail" "good_example" {
        kms_key_id = aws_kms_alias.trail.arn
      }
  bad:
    - |-
      resource "aws_cloudtrail" "bad_example" {
      }
