cloudformation:
  good:
    - |-
      Resources:
        GoodExampleTrail:
          Type: AWS::CloudTrail::Trail
          Properties:
            CloudWatchLogsLogGroupArn: arn:aws:logs:us-east-1:123456789012:log-group:CloudTrail/DefaultLogGroup:*
            TrailName: Cloudtrail
  bad:
    - |-
      Resources:
        BadExampleTrail:
          Type: AWS::CloudTrail::Trail
          Properties:
            TrailName: Cloudtrail
terraform:
  links:
    - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudtrail
  good:
    - |-
      resource "aws_cloudtrail" "good_example" {
        cloud_watch_logs_group_arn = "${aws_cloudwatch_log_group.example.arn}:*"
      }

      resource "aws_cloudwatch_log_group" "example" {
        name = "Example"
      }
  bad:
    - |-
      resource "aws_cloudtrail" "bad_example" {
      }
