cloudformation:
  good:
    - |-
      Resources:
        GoodExampleBucket:
          Type: AWS::S3::Bucket
          Properties:
            AccessControl: Private
            BucketName: my-bucket

        GoodExampleTrail:
          Type: AWS::CloudTrail::Trail
          Properties:
            IsLogging: true
            S3BucketName: my-bucket
            TrailName: Cloudtrail
  bad:
    - |-
      Resources:
        BadExampleBucket:
          Type: AWS::S3::Bucket
          Properties:
            AccessControl: AuthenticatedRead
            BucketName: my-bucket

        BadExampleTrail:
          Type: AWS::CloudTrail::Trail
          Properties:
            IsLogging: true
            S3BucketName: my-bucket
            TrailName: Cloudtrail
terraform:
  links:
    - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudtrail#is_multi_region_trail
  good:
    - |-
      resource "aws_cloudtrail" "good_example" {
        s3_bucket_name = aws_s3_bucket.example.id
      }

      resource "aws_s3_bucket" "example" {
        bucket = "example"
        acl    = "private"
      }
  bad:
    - |-
      resource "aws_cloudtrail" "bad_example" {
        s3_bucket_name = aws_s3_bucket.example.id
      }

      resource "aws_s3_bucket" "example" {
        bucket = "example"
        acl    = "public-read"
      }
