cloudformation:
  links:
    - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-docdb-dbcluster.html
  good:
    - |-
      Resources:
        GoodExample:
          Type: AWS::DocDB::DBCluster
          Properties:
            DBClusterIdentifier: sample-cluster
            DBClusterParameterGroupName: default.docdb3.6
            StorageEncrypted: true

        InstanceInstanceExample:
          Type: AWS::DocDB::DBInstance
          Properties:
            DBClusterIdentifier: sample-cluster
            DBInstanceClass: db.r5.large
            DBInstanceIdentifier: sample-cluster-instance-0
  bad:
    - |-
      Resources:
        BadExample:
          Type: AWS::DocDB::DBCluster
          Properties:
            DBClusterIdentifier: sample-cluster
            DBClusterParameterGroupName: default.docdb3.6

        BadInstanceExample:
          Type: AWS::DocDB::DBInstance
          Properties:
            DBClusterIdentifier: sample-cluster
            DBInstanceClass: db.r5.large
            DBInstanceIdentifier: sample-cluster-instance-0
terraform:
  links:
    - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/docdb_cluster#storage_encrypted
  good:
    - |-
      resource "aws_docdb_cluster" "good_example" {
        cluster_identifier = "my-docdb-cluster"
        master_username    = "foo"
        master_password    = "mustbeeightchars"
        storage_encrypted  = true
      }
  bad:
    - |-
      resource "aws_docdb_cluster" "bad_example" {
        cluster_identifier = "my-docdb-cluster"
        master_username    = "foo"
        master_password    = "mustbeeightchars"
        storage_encrypted  = false
      }
