cloudformation:
  links:
    - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-docdb-dbcluster.html
  good:
    - |-
      Resources:
        GoodExample:
          Type: AWS::DocDB::DBCluster
          Properties:
            DBClusterIdentifier: sample-cluster
            DBClusterParameterGroupName: default.docdb3.6
            KmsKeyId: your-kms-key-id

        InstanceInstanceExample:
          Type: AWS::DocDB::DBInstance
          Properties:
            DBClusterIdentifier: sample-cluster
            DBInstanceClass: db.r5.large
            DBInstanceIdentifier: sample-cluster-instance-0
  bad:
    - |-
      Resources:
        BadExample:
          Type: AWS::DocDB::DBCluster
          Properties:
            DBClusterIdentifier: sample-cluster
            DBClusterParameterGroupName: default.docdb3.6

        BadInstanceExample:
          Type: AWS::DocDB::DBInstance
          Properties:
            DBClusterIdentifier: sample-cluster
            DBInstanceClass: db.r5.large
            DBInstanceIdentifier: sample-cluster-instance-0
terraform:
  links:
    - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/docdb_cluster#kms_key_id
  good:
    - |-
      resource "aws_kms_key" "docdb_encryption" {
        enable_key_rotation = true
      }

      resource "aws_docdb_cluster" "docdb" {
        cluster_identifier = "my-docdb-cluster"
        master_username    = "foo"
        master_password    = "mustbeeightchars"
        kms_key_id         = aws_kms_key.docdb_encryption.arn
      }
  bad:
    - |-
      resource "aws_docdb_cluster" "docdb" {
        cluster_identifier  = "my-docdb-cluster"
        master_username     = "foo"
        master_password     = "mustbeeightchars"
        skip_final_snapshot = true
      }
