cloudformation:
  good:
    - |-
      Resources:
        GoodExample:
          Type: AWS::DAX::Cluster
          Properties:
            ClusterName: MyDAXCluster
            IAMRoleARN: arn:aws:iam::111122223333:role/DaxAccess
            NodeType: dax.r3.large
            ReplicationFactor: 1
            SSESpecification:
              SSEEnabled: true
  bad:
    - |-
      Resources:
        BadExample:
          Type: AWS::DAX::Cluster
          Properties:
            ClusterName: MyDAXCluster
            IAMRoleARN: arn:aws:iam::111122223333:role/DaxAccess
            NodeType: dax.r3.large
            ReplicationFactor: 1
            SubnetGroupName: !Ref subnetGroupClu
terraform:
  links:
    - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dax_cluster#server_side_encryption
  good:
    - |-
      resource "aws_dax_cluster" "good_example" {
        server_side_encryption {
          enabled = true // enabled server side encryption
        }
      }
  bad:
    - |-
      resource "aws_dax_cluster" "bad_example" {
        // no server side encryption at all
      }
    - |-
      resource "aws_dax_cluster" "bad_example" {
        server_side_encryption {
          // empty server side encryption config
        }
      }
    - |-
      resource "aws_dax_cluster" "bad_example" {
        server_side_encryption {
          enabled = false // disabled server side encryption
        }
      }
