---
- id: CMD-0020
  key: kubernetesPKICertificateFilePermissions
  title: Kubernetes PKI certificate file permissions
  nodeType: master
  audit: stat -c %a $(ls -aR $kubelet.cafile |
    awk'/:$/&&f{s=$0;f=0}/:$/&&!f{sub(/:$/,"");s=$0;f=1;next}NF&&f{print
    s"/"$0}' | grep \.crt$)
  platforms:
    - k8s
