---
- id: CMD-0050
  key: kubePKIKeyFilePermissions
  title: Kubernetes PKI certificate file permissions
  nodeType: master
  audit: stat -c %a $(ls -aR /node/etc/kubernetes/ssl | awk
    '/:$/&&f{s=$0;f=0}/:$/&&!f{sub(/:$/,"");s=$0;f=1;next}NF&&f{print s"/"$0}' |
    grep \.key$)
  platforms:
    - rke
