---
- id: CMD-0025
  key: kubeconfigFileExistsOwnership
  title: Kubeconfig file exists ensure ownership
  nodeType: worker
  audit: output=`stat -c %U:%G $(ps -ef | grep $proxy.bins |grep 'kubeconfig' |
    grep -o 'kubeconfig=[^"]\S*' | awk -F "=" '{print $2}' |awk 'FNR <= 1')
    2>/dev/null` || echo $output
  platforms:
    - k8s
    - rke2
