cloudformation:
  good:
    - |-
      Resources:
        GoodExample:
          Type: AWS::Logs::LogGroup
          Properties:
            KmsKeyId: arn:aws:kms:us-west-2:111122223333:key/lambdalogging
            LogGroupName: aws/lambda/goodExample
            RetentionInDays: 30
  bad:
    - |-
      Resources:
        BadExample:
          Type: AWS::Logs::LogGroup
          Properties:
            KmsKeyId: ""
            LogGroupName: aws/lambda/badExample
            RetentionInDays: 30
terraform:
  links:
    - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_log_group#kms_key_id
  good:
    - |-
      resource "aws_kms_key" "cloudwatch" {
        enable_key_rotation = true
      }

      resource "aws_kms_alias" "cloudwatch" {
        name          = "alias/cloudwatch"
        target_key_id = aws_kms_key.cloudwatch.key_id
      }
      resource "aws_cloudwatch_log_group" "good_example" {
        name = "good_example"

        kms_key_id = aws_kms_alias.cloudwatch.arn
      }
  bad:
    - |-
      resource "aws_cloudwatch_log_group" "bad_example" {
        name = "bad_example"

      }
