cloudformation:
  links:
    - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-efs-filesystem.html#cfn-efs-filesystem-encrypted
  good:
    - |-
      Resources:
        GoodExample:
          Type: AWS::EFS::FileSystem
          Properties:
            Encrypted: true
  bad:
    - |-
      Resources:
        BadExample:
          Type: AWS::EFS::FileSystem
          Properties:
            Encrypted: false
terraform:
  links:
    - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/efs_file_system
  good:
    - |-
      resource "aws_efs_file_system" "good_example" {
        name      = "bar"
        encrypted = true
      }
  bad:
    - |-
      resource "aws_efs_file_system" "bad_example" {
        name      = "bar"
        encrypted = false
      }
