terraform:
  links:
    - https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project_iam#google_project_iam_audit_config
  good:
    - |-
      resource "google_project_iam_audit_config" "config" {
        project = "your-project-id"
        service = "allServices"
        audit_log_config {
          log_type = "ADMIN_READ"
        }
        audit_log_config {
          log_type = "DATA_READ"
        }
        audit_log_config {
          log_type = "DATA_WRITE"
        }
      }
    - |-
      resource "google_project_iam_audit_config" "config" {
        project = "your-project-id"
        service = "allServices"
        audit_log_config {
          log_type = "ADMIN_READ"
        }
        audit_log_config {
          log_type = "DATA_READ"
        }
        audit_log_config {
          log_type = "DATA_WRITE"
          exempted_members = [
            "serviceAccount:specific-service@project.iam.gserviceaccount.com",
          ]
        }
      }
  bad:
    - |-
      # No audit configuration - will fail the check
      resource "google_project" "project" {
        name       = "My Project"
        project_id = "your-project-id"
      }
    - |-
      # Missing required log types
      resource "google_project_iam_audit_config" "config" {
        project = "your-project-id"
        service = "allServices"
        audit_log_config {
          log_type = "ADMIN_READ"
        }
        # Missing DATA_READ and DATA_WRITE
      }
    - |-
      # Service scope too limited
      resource "google_project_iam_audit_config" "config" {
        project = "your-project-id"
        service = "cloudresourcemanager.googleapis.com" # Should be "allServices"
        audit_log_config {
          log_type = "ADMIN_READ"
        }
        audit_log_config {
          log_type = "DATA_READ"
        }
        audit_log_config {
          log_type = "DATA_WRITE"
        }
      }
