cloudformation:
  good:
    - |-
      Resources:
        GoodExample:
          Type: AWS::Elasticsearch::Domain
          Properties:
            DomainEndpointOptions:
              TLSSecurityPolicy: Policy-Min-TLS-1-2-2019-07
  bad:
    - |-
      Resources:
        BadExample:
          Type: AWS::Elasticsearch::Domain
terraform:
  links:
    - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticsearch_domain#tls_security_policy
  good:
    - |-
      resource "aws_elasticsearch_domain" "good_example" {
        domain_endpoint_options {
          enforce_https       = true
          tls_security_policy = "Policy-Min-TLS-1-2-2019-07"
        }
      }
  bad:
    - |-
      resource "aws_elasticsearch_domain" "bad_example" {
        domain_endpoint_options {
          enforce_https       = true
          tls_security_policy = "Policy-Min-TLS-1-0-2019-07"
        }
      }
