kubernetes:
  good:
    - |-
      apiVersion: v1
      data:
          config: REDIS_PASSWORD=
      kind: ConfigMap
      metadata:
          name: test
    - |-
      apiVersion: v1
      data:
          env: REDIS_PASSWORD=${REDIS_PASSWORD}
      kind: ConfigMap
      metadata:
          name: test
  bad:
    - |-
      apiVersion: v1
      data:
          password: supersecret
      kind: ConfigMap
      metadata:
          name: test
    - |-
      apiVersion: v1
      data:
          config: REDIS_PASSWORD=abcd1234
      kind: ConfigMap
      metadata:
          name: test
