kubernetes:
  good:
    - |-
      apiVersion: v1
      kind: Ingress
      metadata:
          annotations:
              nginx.ingress.kubernetes.io/auth-url: https://valid-url.com
          name: test-ingress-valid-url
          namespace: default
    - |-
      apiVersion: v1
      kind: Ingress
      metadata:
          annotations:
              nginx.ingress.kubernetes.io/auth-tls-match-cn: CN=valid-cn
          name: test-ingress-valid-cn
          namespace: default
    - |-
      apiVersion: v1
      kind: Ingress
      metadata:
          annotations:
              nginx.ingress.kubernetes.io/mirror-target: https://valid-url.com
          name: test-ingress-valid-target
          namespace: default
    - |-
      apiVersion: v1
      kind: Ingress
      metadata:
          annotations:
              nginx.ingress.kubernetes.io/mirror-host: https://valid-url.com
          name: test-ingress-valid-host
          namespace: default
  bad:
    - |-
      apiVersion: v1
      kind: Ingress
      metadata:
          annotations:
              nginx.ingress.kubernetes.io/auth-url: http://example.com/invalid|url
          name: test-ingress-invalid-url
          namespace: default
    - |-
      apiVersion: v1
      kind: Ingress
      metadata:
          annotations:
              nginx.ingress.kubernetes.io/auth-url: |-
                  http://example.com/#;
                  injection_point
          name: test-ingress-suspicious-char
          namespace: default
    - |-
      apiVersion: v1
      kind: Ingress
      metadata:
          annotations:
              nginx.ingress.kubernetes.io/auth-tls-match-cn: CN=invalid|cn
          name: test-ingress-invalid-cn
          namespace: default
    - |-
      apiVersion: v1
      kind: Ingress
      metadata:
          annotations:
              nginx.ingress.kubernetes.io/auth-tls-match-cn: |-
                  CN=valid#;
                  injection_point
          name: test-ingress-suspicious-char-cn
          namespace: default
    - |-
      apiVersion: v1
      kind: Ingress
      metadata:
          annotations:
              nginx.ingress.kubernetes.io/mirror-target: http://example.com/invalid|url
          name: test-ingress-invalid-target
          namespace: default
    - |-
      apiVersion: v1
      kind: Ingress
      metadata:
          annotations:
              nginx.ingress.kubernetes.io/mirror-target: |-
                  http://example.com/#;
                  injection_point
          name: test-ingress-suspicious-char-target
          namespace: default
    - |-
      apiVersion: v1
      kind: Ingress
      metadata:
          annotations:
              nginx.ingress.kubernetes.io/mirror-host: http://example.com/invalid|url
          name: test-ingress-invalid-host
          namespace: default
    - |-
      apiVersion: v1
      kind: Ingress
      metadata:
          annotations:
              nginx.ingress.kubernetes.io/mirror-host: |-
                  http://example.com/#;
                  injection_point
          name: test-ingress-suspicious-char-host
          namespace: default
