kubernetes:
  good:
    - |-
      apiVersion: v1
      kind: Pod
      metadata:
          name: hello-host-network
      spec:
          containers:
              - command:
                  - sh
                  - -c
                  - echo 'Hello' && sleep 1h
                image: busybox
                name: hello
          hostNetwork: false
  bad:
    - |-
      apiVersion: v1
      kind: Pod
      metadata:
          name: hello-host-network
      spec:
          containers:
              - command:
                  - sh
                  - -c
                  - echo 'Hello' && sleep 1h
                image: busybox
                name: hello
          hostNetwork: true
