kubernetes:
    good:
        - |-
          apiVersion: v1
          kind: Pod
          metadata:
            name: hello-host-network
          spec:
            hostNetwork: false
            containers:
              - command:
                  - sh
                  - "-c"
                  - echo 'Hello' && sleep 1h
                image: busybox
                name: hello
    bad:
        - |-
          apiVersion: v1
          kind: Pod
          metadata:
            name: hello-host-network
          spec:
            hostNetwork: true
            containers:
              - command:
                  - sh
                  - "-c"
                  - echo 'Hello' && sleep 1h
                image: busybox
                name: hello
