kubernetes:
    good:
        - |-
          apiVersion: v1
          kind: Pod
          metadata:
            name: hello-sysctls
          spec:
            securityContext:
              sysctls:
                - name: kernel.shm_rmid_forced
                  value: '0'
            containers:
              - command:
                  - sh
                  - "-c"
                  - echo 'Hello' && sleep 1h
                image: busybox
                name: hello
    bad:
        - |-
          apiVersion: v1
          kind: Pod
          metadata:
            name: hello-sysctls
          spec:
            securityContext:
              sysctls:
                - name: net.core.somaxconn
                  value: '1024'
                - name: kernel.msgmax
                  value: '65536'
            containers:
              - command:
                  - sh
                  - "-c"
                  - echo 'Hello' && sleep 1h
                image: busybox
                name: hello
