cloudformation:
  good:
    - |-
      Resources:
        GoodExample:
          Type: AWS::S3::Bucket
          Properties:
            PublicAccessBlockConfiguration:
              BlockPublicAcls: true
              BlockPublicPolicy: true
              IgnorePublicAcls: true
              RestrictPublicBuckets: true
  bad:
    - |-
      Resources:
        BadExample:
          Type: AWS::S3::Bucket
          Properties:
            AccessControl: AuthenticatedRead
terraform:
  good:
    - |-
      resource "aws_s3_bucket" "good_example" {
        bucket = "mybucket"
      }

      resource "aws_s3_bucket_public_access_block" "good_example" {
        bucket            = aws_s3_bucket.good_example.id
        block_public_acls = true
      }
  bad:
    - |-
      resource "aws_s3_bucket" "bad_example" {
        bucket = "mybucket"
      }

      resource "aws_s3_bucket_public_access_block" "bad_example" {
        bucket = aws_s3_bucket.bad_example.id
      }
    - |-
      resource "aws_s3_bucket" "bad_example" {
        bucket = "mybucket"
      }

      resource "aws_s3_bucket_public_access_block" "bad_example" {
        bucket            = aws_s3_bucket.bad_example.id
        block_public_acls = false
      }
