terraform:
  good:
    - |-
      resource "aws_s3_bucket" "good_example" {
        bucket = "mybucket"
      }

      resource "aws_s3_bucket_public_access_block" "good_example" {
        bucket            = aws_s3_bucket.good_example.id
        block_public_acls = true
      }
  bad:
    - |-
      resource "aws_s3_bucket" "bad_example" {
        bucket = "mybucket"
      }

      resource "aws_s3_bucket_public_access_block" "bad_example" {
        bucket = aws_s3_bucket.bad_example.id
      }
    - |-
      resource "aws_s3_bucket" "bad_example" {
        bucket = "mybucket"
      }

      resource "aws_s3_bucket_public_access_block" "bad_example" {
        bucket            = aws_s3_bucket.bad_example.id
        block_public_acls = false
      }
cloudformation:
  good:
    - |
      Resources:
          GoodExample:
              Properties:
                  PublicAccessBlockConfiguration:
                      BlockPublicAcls: true
                      BlockPublicPolicy: true
                      IgnorePublicAcls: true
                      RestrictPublicBuckets: true
              Type: AWS::S3::Bucket
  bad:
    - |
      Resources:
          BadExample:
              Properties:
                  AccessControl: AuthenticatedRead
              Type: AWS::S3::Bucket
