cloudformation:
  good:
    - |-
      Resources:
        GoodExample:
          Type: AWS::S3::Bucket
          Properties:
            PublicAccessBlockConfiguration:
              BlockPublicPolicy: true
  bad:
    - |-
      Resources:
        BadExample:
          Type: AWS::S3::Bucket
terraform:
  links:
    - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_public_access_block#block_public_policy
  good:
    - |-
      resource "aws_s3_bucket" "example" {
        bucket = "mybucket"
      }

      resource "aws_s3_bucket_public_access_block" "good_example" {
        bucket              = aws_s3_bucket.example.id
        block_public_policy = true
      }
  bad:
    - |-
      resource "aws_s3_bucket" "example" {
        bucket = "mybucket"
      }

      resource "aws_s3_bucket_public_access_block" "bad_example" {
        bucket = aws_s3_bucket.example.id
      }
    - |-
      resource "aws_s3_bucket" "example" {
        bucket = "mybucket"
      }
      resource "aws_s3_bucket_public_access_block" "bad_example" {
        bucket              = aws_s3_bucket.example.id
        block_public_policy = false
      }
