cloudformation:
  good:
    - |-
      Resources:
        GoodExample:
          Type: AWS::S3::Bucket
          Properties:
            VersioningConfiguration:
              Status: Enabled
  bad:
    - |-
      Resources:
        BadExample:
          Type: AWS::S3::Bucket
terraform:
  links:
    - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket#versioning
  good:
    - |-
      resource "aws_s3_bucket" "good_example" {
        versioning {
          enabled = true
        }
      }
    - |-
      resource "aws_s3_bucket" "good_example" {
        bucket = "yournamehere"
      }

      resource "aws_s3_bucket_versioning" "example" {
        bucket = aws_s3_bucket.good_example.id
        versioning_configuration {
          status = "Enabled"
        }
      }
  bad:
    - |-
      resource "aws_s3_bucket" "bad_example" {

      }
    - |-
      resource "aws_s3_bucket" "bad_example" {
        versioning {
          enabled = false
        }
      }
    - |-
      resource "aws_s3_bucket" "bad_example" {
        bucket = "yournamehere"
      }

      resource "aws_s3_bucket_versioning" "example" {
        bucket = aws_s3_bucket.bad_example.id
        versioning_configuration {
          status = "Disabled"
        }
      }
