cloudformation:
  good:
    - |-
      Resources:
        GoodExample:
          Type: AWS::S3::Bucket
          Properties:
            BucketEncryption:
              ServerSideEncryptionConfiguration:
                - BucketKeyEnabled: true
                  ServerSideEncryptionByDefault:
                    KMSMasterKeyID: kms-arn
                    SSEAlgorithm: aws:kms
  bad:
    - |-
      Resources:
        BadExample:
          Type: AWS::S3::Bucket
          Properties:
            BucketEncryption:
              ServerSideEncryptionConfiguration:
                - BucketKeyEnabled: false
                  ServerSideEncryptionByDefault:
                    SSEAlgorithm: AES256
terraform:
  links:
    - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket#enable-default-server-side-encryption
  good:
    - |-
      resource "aws_kms_key" "mykey" {}

      resource "aws_s3_bucket" "good_example" {
        bucket = "mybucket"
      }

      resource "aws_s3_bucket_server_side_encryption_configuration" "example" {
        bucket = aws_s3_bucket.good_example.id

        rule {
          apply_server_side_encryption_by_default {
            kms_master_key_id = aws_kms_key.mykey.arn
            sse_algorithm     = "aws:kms"
          }
        }
      }
    - |-
      resource "aws_s3_bucket" "good_example" {
        # server access logging bucket
        acl    = "log-delivery-write"
        bucket = "mybucket"
      }

      resource "aws_s3_bucket_server_side_encryption_configuration" "example" {
        bucket = aws_s3_bucket.good_example.id

        rule {
          apply_server_side_encryption_by_default {
            sse_algorithm = "AES256"
          }
        }
      }
    - |-
      resource "aws_kms_key" "good_example" {
        enable_key_rotation = true
      }

      resource "aws_s3_bucket" "good_example" {
        bucket = "mybucket"

        # deprecated way
        server_side_encryption_configuration {
          rule {
            apply_server_side_encryption_by_default {
              kms_master_key_id = aws_kms_key.example.arn
              sse_algorithm     = "aws:kms"
            }
          }
        }
      }
    - |-
      resource "aws_s3_bucket" "good_example" {
        bucket = "log-bucket"
      }

      resource "aws_s3_bucket_acl" "log_acl" {
        bucket = aws_s3_bucket.good_example.id
        access_control_policy {

          grant {
            grantee {
              type = "Group"
              uri  = "http://acs.amazonaws.com/groups/s3/LogDelivery"
            }
            permission = "WRITE"
          }

          owner {
            id = data.aws_canonical_user_id.current.id
          }
        }
      }

      resource "aws_s3_bucket_server_side_encryption_configuration" "sse_config" {
        bucket = aws_s3_bucket.good_example.id

        rule {
          apply_server_side_encryption_by_default {
            sse_algorithm = "AES256"
          }
        }
      }
    - |-
      resource "aws_s3_bucket" "good_example" {
        bucket = "log-policy-bucket"
      }

      resource "aws_s3_bucket_policy" "log_policy" {
        bucket = aws_s3_bucket.good_example.id
        policy = jsonencode({
          Version = "2012-10-17"
          Statement = [{
            Effect = "Allow"
            Principal = {
              Service = "logging.s3.amazonaws.com"
            }
            Action   = "s3:PutObject"
            Resource = "arn:aws:s3:::log-policy-bucket/logs/*"
          }]
        })
      }

      resource "aws_s3_bucket_server_side_encryption_configuration" "sse_config" {
        bucket = aws_s3_bucket.good_example.id

        rule {
          apply_server_side_encryption_by_default {
            sse_algorithm = "AES256"
          }
        }
      }
  bad:
    - |-
      resource "aws_s3_bucket" "bad_example" {
        bucket = "mybucket"
      }

      resource "aws_s3_bucket_server_side_encryption_configuration" "example" {
        bucket = aws_s3_bucket.bad_example.id

        rule {
          apply_server_side_encryption_by_default {
            sse_algorithm = "AES256"
          }
        }
      }
    - |-
      resource "aws_s3_bucket" "bad_exampl" {
        bucket = "mybucket"

        # deprecated way
        server_side_encryption_configuration {
          rule {
            apply_server_side_encryption_by_default {
              sse_algorithm = "AES256"
            }
          }
        }
      }
