cloudformation:
  good:
    - |-
      Resources:
        GoodExample:
          Type: AWS::S3::Bucket
          Properties:
            PublicAccessBlockConfiguration:
              BlockPublicAcls: true
              BlockPublicPolicy: true
              IgnorePublicAcls: true
              RestrictPublicBuckets: true
  bad:
    - |-
      Resources:
        BadExample:
          Properties:
            AccessControl: AuthenticatedRead

        Type: AWS::S3::Bucket
terraform:
  good:
    - |-
      resource "aws_s3_bucket" "example" {
        bucket = "bucket"
      }

      resource "aws_s3_bucket_public_access_block" "good_example" {
        bucket = aws_s3_bucket.example.id

        restrict_public_buckets = true
      }
  bad:
    - |-
      resource "aws_s3_bucket" "example" {
        bucket = "bucket"
      }

      resource "aws_s3_bucket_public_access_block" "bad_example" {
        bucket = aws_s3_bucket.example.id
      }

      resource "aws_s3_bucket_public_access_block" "bad_example" {
        bucket = aws_s3_bucket.example.id

        restrict_public_buckets = false
      }
