cloudformation:
  good:
    - |-
      Resources:
        GoodExample:
          Type: AWS::Serverless::Api
          Properties:
            Domain:
              SecurityPolicy: TLS_1_2
            Name: Good SAM API example
            StageName: Prod
            TracingEnabled: false
    - |-
      Resources:
        GoodExample:
          Type: AWS::Serverless::Api
          Properties:
            Domain:
              SecurityPolicy: SecurityPolicy_TLS13_1_2_2021_06
            Name: Good SAM API example
            StageName: Prod
            TracingEnabled: false
    - |-
      Resources:
        GoodExample:
          Type: AWS::Serverless::Api
          Properties:
            Domain:
              SecurityPolicy: SecurityPolicy_TLS13_2025_EDGE
            Name: Good SAM API example
            StageName: Prod
            TracingEnabled: false
  bad:
    - |-
      Resources:
        BadExample:
          Type: AWS::Serverless::Api
          Properties:
            Name: Bad SAM API example
            StageName: Prod
            TracingEnabled: false