cloudformation:
  good:
    - |
      Resources:
        GoodExample:
          Properties:
            Domain:
              SecurityPolicy: TLS_1_2
            Name: Good SAM API example
            StageName: Prod
            TracingEnabled: false
          Type: AWS::Serverless::Api
  bad:
    - |
      Resources:
        BadExample:
          Properties:
            Name: Bad SAM API example
            StageName: Prod
            TracingEnabled: false
          Type: AWS::Serverless::Api
