cloudformation:
  good:
    - |-
      Resources:
        GoodExample:
          Type: AWS::Serverless::Api
          Properties:
            Domain:
              SecurityPolicy: TLS_1_2
            MethodSettings:
              CacheDataEncrypted: true
            Name: Good SAM API example
            StageName: Prod
            TracingEnabled: false
  bad:
    - |-
      Resources:
        BadExample:
          Type: AWS::Serverless::Api
          Properties:
            Name: Bad SAM API example
            StageName: Prod
            TracingEnabled: false
    - |-
      Resources:
        BadExample:
          Type: AWS::Serverless::Api
          Properties:
            MethodSettings:
              CacheDataEncrypted: false
            Name: Bad SAM API example
            StageName: Prod
            TracingEnabled: false
