cloudformation:
  good:
    - |-
      Resources:
        GoodExample:
          Type: AWS::Serverless::HttpApi
          Properties:
            AccessLogSettings:
              DestinationArn: gateway-logging
              Format: json
            Name: Good SAM API example
            StageName: Prod
            Tracing: Activey
  bad:
    - |-
      Resources:
        BadExample:
          Type: AWS::Serverless::HttpApi
          Properties:
            Name: Good SAM API example
            StageName: Prod
            Tracing: Passthrough
