cloudformation:
  good:
    - |-
      Resources:
        GoodExample:
          Type: AWS::Serverless::Api
          Properties:
            MethodSettings:
              CacheDataEncrypted: true
            Name: Good SAM API example
            StageName: Prod
  bad:
    - |-
      Resources:
        BadExample:
          Type: AWS::Serverless::Api
          Properties:
            Name: Bad SAM API example
            StageName: Prod
    - |-
      Resources:
        BadExample:
          Type: AWS::Serverless::Api
          Properties:
            MethodSettings:
              CacheDataEncrypted: false
            Name: Bad SAM API example
            StageName: Prod
