cloudformation:
  good:
    - |-
      Resources:
          GoodFunction:
              Properties:
                  Definition:
                      StartAt: MyLambdaState
                      States:
                          MyLambdaState:
                              End: true
                              Resource: arn:aws:lambda:us-east-1:123456123456:function:my-sample-lambda-app
                              Type: Task
                  Policies:
                      - AWSLambdaExecute
                      - Statement:
                          - Action:
                              - s3:GetObject
                              - s3:GetObjectACL
                            Effect: Allow
                            Resource: arn:aws:s3:::my-bucket/*
                        Version: "2012-10-17"
                  Role: arn:aws:iam::123456123456:role/service-role/my-sample-role
                  Tracing:
                      Enabled: true
              Type: AWS::Serverless::StateMachine
  bad:
    - |-
      Resources:
          BadFunction:
              Properties:
                  Definition:
                      StartAt: MyLambdaState
                      States:
                          MyLambdaState:
                              End: true
                              Resource: arn:aws:lambda:us-east-1:123456123456:function:my-sample-lambda-app
                              Type: Task
                  Policies:
                      - AWSLambdaExecute
                      - Statement:
                          - Action:
                              - s3:*
                            Effect: Allow
                            Resource: arn:aws:s3:::my-bucket/*
                        Version: "2012-10-17"
                  Role: arn:aws:iam::123456123456:role/service-role/my-sample-role
                  Tracing:
                      Enabled: true
              Type: AWS::Serverless::StateMachine
