kubernetes:
  good:
    - |-
      apiVersion: v1
      kind: Pod
      metadata:
          labels:
              name: mypod
          name: mypod
          namespace: test
      spec:
          automountServiceAccountToken: true
          containers:
              - image: nginx
                name: mypod
  bad:
    - |-
      apiVersion: v1
      kind: Pod
      metadata:
          labels:
              name: mypod
          name: mypod
          namespace: kube-system
      spec:
          containers:
              - image: nginx
                name: mypod
