cloudformation:
  links:
    - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-loadbalancer.html
  good:
    - |-
      Resources:
        GoodExample:
          Type: AWS::ElasticLoadBalancingV2::LoadBalancer
          Properties:
            LoadBalancerAttributes:
              - Key: routing.http.drop_invalid_header_fields.enabled
                Value: true
    - |-
      Resources:
        GoodExample:
          Type: AWS::ElasticLoadBalancingV2::LoadBalancer
          Properties:
            Type: gateway
  bad:
    - |-
      Resources:
        BadExample:
          Type: AWS::ElasticLoadBalancingV2::LoadBalancer
          Properties:
            LoadBalancerAttributes:
              - Key: routing.http.drop_invalid_header_fields.enabled
                Value: false
terraform:
  links:
    - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb#drop_invalid_header_fields
  good:
    - |-
      resource "aws_alb" "good_example" {
        drop_invalid_header_fields = true
      }
  bad:
    - |-
      resource "aws_alb" "bad_example" {
        drop_invalid_header_fields = false
      }
