cloudformation:
  links:
    - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-listener.html
  good:
    - |-
      Resources:
        myLoadBalancer:
          Type: AWS::ElasticLoadBalancingV2::LoadBalancer

        GoodExample:
          Type: AWS::ElasticLoadBalancingV2::Listener
          Properties:
            LoadBalancerArn: !Ref myLoadBalancer
            Protocol: HTTPS
            SslPolicy: ELBSecurityPolicy-TLS13-1-2-2021-06
  bad:
    - |-
      Resources:
        myLoadBalancer:
          Type: AWS::ElasticLoadBalancingV2::LoadBalancer

        BadExample:
          Type: AWS::ElasticLoadBalancingV2::Listener
          Properties:
            LoadBalancerArn: !Ref myLoadBalancer
            Protocol: HTTPS
            SslPolicy: ELBSecurityPolicy-TLS-1-1-2017-01
terraform:
  links:
    - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_listener
  good:
    - |-
      resource "aws_lb" "example" {}

      resource "aws_alb_listener" "good_example" {
        load_balancer_arn = aws_lb.example.arn
        ssl_policy        = "ELBSecurityPolicy-TLS13-1-2-2021-06"
        protocol          = "HTTPS"
      }
  bad:
    - |-
      resource "aws_lb" "example" {}

      resource "aws_alb_listener" "bad_example" {
        load_balancer_arn = aws_lb.example.arn
        ssl_policy        = "ELBSecurityPolicy-TLS-1-1-2017-01"
        protocol          = "HTTPS"
      }
