cloudformation:
  good:
    - |-
      Resources:
        GoodExample:
          Type: AWS::AutoScaling::LaunchConfiguration
          Properties:
            MetadataOptions:
              HttpEndpoint: enabled
              HttpTokens: required
  bad:
    - |-
      Resources:
        BadExample:
          Type: AWS::AutoScaling::LaunchConfiguration
          Properties:
            MetadataOptions:
              HttpEndpoint: enabled
              HttpTokens: optional
terraform:
  good:
    - |-
      resource "aws_launch_template" "good_example" {
        image_id      = "ami-005e54dee72cc1d00"
        instance_type = "t2.micro"
        metadata_options {
          http_tokens = "required"
        }
      }
  bad:
    - |-
      resource "aws_launch_template" "bad_example" {
        image_id      = "ami-005e54dee72cc1d00"
        instance_type = "t2.micro"
      }
