cloudformation:
  good:
    - |-
      Resources:
        GoodExample:
          Type: AWS::AutoScaling::LaunchConfiguration
          Properties:
            BlockDeviceMappings:
              - DeviceName: root
                Ebs:
                  Encrypted: true
            ImageId: ami-123456
            InstanceType: t2.small
  bad:
    - |-
      Resources:
        BadExample:
          Type: AWS::AutoScaling::LaunchConfiguration
          Properties:
            BlockDeviceMappings:
              - DeviceName: root
                Ebs:
                  Encrypted: true
              - DeviceName: data
                Ebs:
                  Encrypted: false
            ImageId: ami-123456
            InstanceType: t2.small
terraform:
  good:
    - |-
      resource "aws_launch_configuration" "good_example" {
        root_block_device {
          encrypted = true
        }
      }
  bad:
    - |-
      resource "aws_launch_configuration" "bad_example" {
        root_block_device {
          encrypted = false
        }
      }
