cloudformation:
  good:
    - |-
      Resources:
        GoodExample:
          Type: AWS::EC2::LaunchTemplate
          Properties:
            LaunchTemplateData:
              DisableApiTermination: true
              IamInstanceProfile:
                Arn:
                  - MyIamInstanceProfile
                  - Arn
              ImageId: ami-04d5cc9b88example
              InstanceType: t2.micro
              KeyName: MyKeyPair
              MetadataOptions:
                - HttpTokens: required
              SecurityGroupIds:
                - sg-083cd3bfb8example
              UserData: export SSM_PATH=/database/creds
            LaunchTemplateName: MyLaunchTemplate

        InstanceProfile:
          Type: AWS::IAM::InstanceProfile
          Properties:
            InstanceProfileName: MyIamInstanceProfile
            Path: /
            Roles:
              - MyAdminRole
  bad:
    - |-
      Resources:
        BadExample:
          Type: AWS::EC2::LaunchTemplate
          Properties:
            LaunchTemplateData:
              DisableApiTermination: true
              IamInstanceProfile:
                Arn:
                  - MyIamInstanceProfile
                  - Arn
              ImageId: ami-04d5cc9b88example
              InstanceType: t2.micro
              KeyName: MyKeyPair
              SecurityGroupIds:
                - sg-083cd3bfb8example
              UserData: export DATABASE_PASSWORD=password1234
            LaunchTemplateName: MyLaunchTemplate

        InstanceProfile:
          Type: AWS::IAM::InstanceProfile
          Properties:
            InstanceProfileName: MyIamInstanceProfile
            Path: /
            Roles:
              - MyAdminRole
terraform:
  good:
    - |-
      resource "aws_iam_instance_profile" "good_example" {
        // ...
      }

      resource "aws_launch_template" "good_example" {
        image_id      = "ami-12345667"
        instance_type = "t2.small"

        iam_instance_profile {
          name = aws_iam_instance_profile.good_profile.arn
        }
        user_data = <<EOF
      	 export GREETING=hello
      EOF
      }
  bad:
    - "resource \"aws_launch_template\" \"bad_example\" {\n  image_id      = \"ami-12345667\"\n  instance_type = \"t2.small\"\n\n  user_data = <<EOF\n export AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE\n export AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY\n export AWS_DEFAULT_REGION=us-west-2 \nEOF\n}"
