cloudformation:
  good:
    - |-
      Resources:
        GoodExample:
          DeletionPolicy: Snapshot
          Type: AWS::EC2::Volume
          Properties:
            Encrypted: true
  bad:
    - |-
      Resources:
        BadExample:
          DeletionPolicy: Snapshot
          Type: AWS::EC2::Volume
terraform:
  links:
    - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ebs_volume#encrypted
  good:
    - |-
      resource "aws_ebs_volume" "good_example" {
        encrypted = true
      }
  bad:
    - |-
      resource "aws_ebs_volume" "bad_example" {
        encrypted = false
      }
