cloudformation:
  good:
    - |-
      Resources:
        GoodExample:
          Type: AWS::EC2::Instance
          Properties:
            BlockDeviceMappings:
              - DeviceName: /dev/sdm
                Ebs:
                  Encrypted: true
            ImageId: ami-79fd7eee
  bad:
    - |-
      Resources:
        BadExample:
          Type: AWS::EC2::Instance
          Properties:
            BlockDeviceMappings:
              - DeviceName: /dev/sdm
                Ebs:
                  Encrypted: false
            ImageId: ami-79fd7eee
terraform:
  links:
    - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#ebs-ephemeral-and-root-block-devices
  good:
    - |-
      resource "aws_instance" "good_example" {
        ami           = "ami-7f89a64f"
        instance_type = "t1.micro"

        root_block_device {
          encrypted = true
        }

        ebs_block_device {
          device_name = "/dev/sdg"
          encrypted   = true
        }
      }
  bad:
    - |-
      resource "aws_instance" "bad_example" {
        ami           = "ami-7f89a64f"
        instance_type = "t1.micro"

        root_block_device {
          encrypted = false
        }

        ebs_block_device {
          device_name = "/dev/sdg"
          encrypted   = false
        }
      }
