cloudformation:
  good:
    - |-
      Resources:
        GoodExample:
          Type: AWS::EC2::Volume
          Properties:
            KmsKeyId: alias/volumeEncrypt
    - |-
      Resources:
        MyKey:
          Type: AWS::KMS::Key
          Properties:
            KeyPolicy:
              Version: "2012-10-17"
              Id: key-default-1

        GoodExample:
          Type: AWS::EC2::Volume
          Properties:
            KmsKeyId: !Ref MyKey
  bad:
    - |-
      Resources:
        BadExample:
          Type: AWS::EC2::Volume
terraform:
  links:
    - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ebs_volume#kms_key_id
  good:
    - |-
      resource "aws_kms_key" "ebs_encryption" {
        enable_key_rotation = true
      }

      resource "aws_ebs_volume" "example" {
        kms_key_id = aws_kms_key.ebs_encryption.arn
      }
  bad:
    - |-
      resource "aws_ebs_volume" "example" {}
