cloudformation:
  good:
    - |-
      AWSTemplateFormatVersion: "2010-09-09"

      Resources:
        NetworkACL:
          Type: AWS::EC2::NetworkAcl
          Properties:
            RuleAction: allow
            VpcId: something

        Rule:
          Type: AWS::EC2::NetworkAclEntry
          Properties:
            NetworkAclId: !Ref NetworkACL
            Protocol: 6
            Ref: NetworkACL
            RuleAction: allow
  bad:
    - |-
      AWSTemplateFormatVersion: "2010-09-09"

      Resources:
        NetworkACL:
          Type: AWS::EC2::NetworkAcl
          Properties:
            RuleAction: allow
            VpcId: something

        Rule:
          Type: AWS::EC2::NetworkAclEntry
          Properties:
            NetworkAclId: !Ref NetworkACL
            Protocol: -1
            Ref: NetworkACL
            RuleAction: allow
terraform:
  links:
    - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/network_acl_rule#to_port
  good:
    - |-
      resource "aws_network_acl_rule" "good_example" {
        egress      = false
        protocol    = "tcp"
        from_port   = 22
        to_port     = 22
        rule_action = "allow"
        cidr_block  = "0.0.0.0/0"
      }
  bad:
    - |-
      resource "aws_network_acl_rule" "bad_example" {
        egress      = false
        protocol    = "all"
        rule_action = "allow"
        cidr_block  = "0.0.0.0/0"
      }
