cloudformation:
  links:
    - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-securitygroup.html
  good:
    - |-
      AWSTemplateFormatVersion: "2010-09-09"

      Resources:
        BadSecurityGroup:
          Type: AWS::EC2::SecurityGroup
          Properties:
            GroupDescription: Limits security group egress traffic
            SecurityGroupEgress:
              - CidrIp: 127.0.0.1/32
                IpProtocol: "6"
  bad:
    - |-
      AWSTemplateFormatVersion: "2010-09-09"

      Resources:
        BadSecurityGroup:
          Type: AWS::EC2::SecurityGroup
          Properties:
            GroupDescription: Limits security group egress traffic
            SecurityGroupEgress:
              - CidrIp: 0.0.0.0/0
                IpProtocol: "6"
terraform:
  links:
    - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group
  good:
    - |-
      resource "aws_security_group" "good_example" {
        egress {
          cidr_blocks = ["1.2.3.4/32"]
        }
      }
  bad:
    - |-
      resource "aws_security_group" "bad_example" {
        egress {
          cidr_blocks = ["0.0.0.0/0"]
        }
      }
