cloudformation:
  good:
    - |-
      AWSTemplateFormatVersion: "2010-09-09"

      Description: Godd example of excessive ports

      Resources:
        NetworkACL:
          Type: AWS::EC2::NetworkAcl
          Properties:
            VpcId: something

        Rule:
          Type: AWS::EC2::NetworkAclEntry
          Properties:
            CidrBlock: 10.0.0.0/8
            NetworkAclId: !Ref NetworkACL
            Protocol: 6
            RuleAction: allow
  bad:
    - |-
      AWSTemplateFormatVersion: "2010-09-09"

      Description: Bad example of excessive ports

      Resources:
        NetworkACL:
          Type: AWS::EC2::NetworkAcl
          Properties:
            VpcId: something

        Rule:
          Type: AWS::EC2::NetworkAclEntry
          Properties:
            CidrBlock: 0.0.0.0/0
            NetworkAclId: !Ref NetworkACL
            Protocol: 6
            RuleAction: allow
terraform:
  good:
    - |-
      resource "aws_network_acl_rule" "good_example" {
        egress      = false
        protocol    = "tcp"
        from_port   = 22
        to_port     = 22
        rule_action = "allow"
        cidr_block  = "10.0.0.0/16"
      }
  bad:
    - |-
      resource "aws_network_acl_rule" "bad_example" {
        egress      = false
        protocol    = "tcp"
        from_port   = 22
        to_port     = 22
        rule_action = "allow"
        cidr_block  = "0.0.0.0/0"
      }
