cloudformation:
  good:
    - |-
      Resources:
        GoodExample:
          Type: AWS::AutoScaling::LaunchConfiguration
          Properties:
            ImageId: ami-123456
            InstanceType: t2.small
  bad:
    - |-
      Resources:
        BadExample:
          Type: AWS::AutoScaling::LaunchConfiguration
          Properties:
            AssociatePublicIpAddress: true
            ImageId: ami-123456
            InstanceType: t2.small
terraform:
  links:
    - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_configuration#associate_public_ip_address
    - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#associate_public_ip_address
  good:
    - |-
      resource "aws_launch_configuration" "good_example" {
        associate_public_ip_address = false
      }
  bad:
    - |-
      resource "aws_launch_configuration" "bad_example" {
        associate_public_ip_address = true
      }
