cloudformation:
  links:
    - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-subnet.html
  good:
    - |-
      Resources:
        GoodExample:
          Type: AWS::EC2::Subnet
          Properties:
            VpcId: vpc-123456
  bad:
    - |-
      Resources:
        BadExample:
          Type: AWS::EC2::Subnet
          Properties:
            MapPublicIpOnLaunch: true
            VpcId: vpc-123456
terraform:
  links:
    - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/subnet#map_public_ip_on_launch
  good:
    - |-
      resource "aws_subnet" "good_example" {
        vpc_id                  = "vpc-123456"
        map_public_ip_on_launch = false
      }
  bad:
    - |-
      resource "aws_subnet" "bad_example" {
        vpc_id                  = "vpc-123456"
        map_public_ip_on_launch = true
      }
