cloudformation:
  good:
    - |-
      Resources:
        GoodExample:
          Type: AWS::EC2::Instance
          Properties:
            BlockDeviceMappings:
              - DeviceName: /dev/sdm
                Ebs:
                  DeleteOnTermination: "false"
                  Iops: "200"
                  VolumeSize: "20"
                  VolumeType: io1
              - DeviceName: /dev/sdk
            ImageId: ami-79fd7eee
            KeyName: testkey
            UserData: export SSM_PATH=/database/creds
  bad:
    - |-
      Resources:
        BadExample:
          Type: AWS::EC2::Instance
          Properties:
            BlockDeviceMappings:
              - DeviceName: /dev/sdm
                Ebs:
                  DeleteOnTermination: "false"
                  Iops: "200"
                  VolumeSize: "20"
                  VolumeType: io1
              - DeviceName: /dev/sdk
            ImageId: ami-79fd7eee
            KeyName: testkey
            UserData: export DATABASE_PASSWORD=password1234
terraform:
  good:
    - |-
      resource "aws_iam_instance_profile" "good_example" {
        // ...
      }

      resource "aws_instance" "good_example" {
        ami           = "ami-12345667"
        instance_type = "t2.small"

        iam_instance_profile = aws_iam_instance_profile.good_profile.arn

        user_data = <<EOF
      	 export GREETING=hello
       EOF
      }
  bad:
    - "resource \"aws_instance\" \"bad_example\" {\n  ami           = \"ami-12345667\"\n  instance_type = \"t2.small\"\n\n  user_data = <<EOF\n export AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE\n export AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY\n export AWS_DEFAULT_REGION=us-west-2 \n EOF\n}"
