cloudformation:
  good:
    - |-
      Resources:
        GoodExample:
          Type: AWS::Kinesis::Stream
          Properties:
            Name: GoodExample
            RetentionPeriodHours: 168
            ShardCount: 3
            StreamEncryption:
              EncryptionType: KMS
              KeyId: alis/key
            Tags:
              - Key: Environment
                Value: Production
  bad:
    - |-
      Resources:
        BadExample:
          Type: AWS::Kinesis::Stream
          Properties:
            Name: BadExample
            RetentionPeriodHours: 168
            ShardCount: 3
            Tags:
              - Key: Environment
                Value: Production
terraform:
  links:
    - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kinesis_stream#encryption_type
  good:
    - |-
      resource "aws_kinesis_stream" "good_example" {
        encryption_type = "KMS"
        kms_key_id      = "my/special/key"
      }
  bad:
    - |-
      resource "aws_kinesis_stream" "bad_example" {
        encryption_type = "NONE"
      }
