cloudformation:
  good:
    - |-
      Resources:
        GoodCluster:
          Type: AWS::Neptune::DBCluster
          Properties:
            EnableCloudwatchLogsExports:
              - audit
  bad:
    - |-
      Resources:
        BadCluster:
          Type: AWS::Neptune::DBCluster
          Properties:
            EnableCloudwatchLogsExports:
              - debug
terraform:
  links:
    - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/neptune_cluster#enable_cloudwatch_logs_exports
  good:
    - |-
      resource "aws_neptune_cluster" "good_example" {
        enable_cloudwatch_logs_exports = ["audit"]
      }
  bad:
    - |-
      resource "aws_neptune_cluster" "bad_example" {}
    - |-
      resource "aws_neptune_cluster" "bad_example" {
        enable_cloudwatch_logs_exports = ["debug"]
      }
