cloudformation:
  good:
    - |-
      Resources:
        GoodCluster:
          Type: AWS::Neptune::DBCluster
          Properties:
            KmsKeyId: something
            StorageEncrypted: true
  bad:
    - |-
      Resources:
        BadCluster:
          Type: AWS::Neptune::DBCluster
          Properties:
            StorageEncrypted: false
terraform:
  good:
    - |-
      resource "aws_neptune_cluster" "good_example" {
        cluster_identifier                  = "neptune-cluster-demo"
        engine                              = "neptune"
        backup_retention_period             = 5
        preferred_backup_window             = "07:00-09:00"
        skip_final_snapshot                 = true
        iam_database_authentication_enabled = true
        apply_immediately                   = true
        storage_encrypted                   = true
        kms_key_arn                         = true
      }
  bad:
    - |-
      resource "aws_neptune_cluster" "bad_example" {
        cluster_identifier                  = "neptune-cluster-demo"
        engine                              = "neptune"
        backup_retention_period             = 5
        preferred_backup_window             = "07:00-09:00"
        skip_final_snapshot                 = true
        iam_database_authentication_enabled = true
        apply_immediately                   = true
        storage_encrypted                   = false
      }
