cloudformation:
  links:
    - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-cluster.html#cfn-eks-cluster-logging
  good:
    - |-
      Resources:
        GoodExample:
          Type: AWS::EKS::Cluster
          Properties:
            Logging:
              ClusterLogging:
                EnabledTypes:
                  - Type: api
                  - Type: audit
                  - Type: authenticator
                  - Type: controllerManager
                  - Type: scheduler
  bad:
    - |-
      Resources:
        BadExample:
          Type: AWS::EKS::Cluster
terraform:
  links:
    - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster#enabled_cluster_log_types
  good:
    - |-
      resource "aws_eks_cluster" "good_example" {
        enabled_cluster_log_types = ["api", "authenticator", "audit", "scheduler", "controllerManager"]
      }
  bad:
    - |-
      resource "aws_eks_cluster" "bad_example" {}
