cloudformation:
  good:
    - |-
      Resources:
        GoodExample:
          Type: AWS::EKS::Cluster
          Properties:
            EncryptionConfig:
              - Provider:
                  KeyArn: alias/eks-kms
                Resources:
                  - secrets
            Name: goodExample
  bad:
    - |-
      Resources:
        BadExample:
          Type: AWS::EKS::Cluster
          Properties:
            Name: badExample
terraform:
  links:
    - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster#encryption_config
  good:
    - |-
      resource "aws_kms_key" "eks" {
        enable_key_rotation = true
      }

      resource "aws_eks_cluster" "good_example" {
        encryption_config {
          resources = ["secrets"]
          provider {
            key_arn = aws_kms_key.eks.arn
          }
        }
      }
  bad:
    - |-
      resource "aws_eks_cluster" "bad_example" {
        name = "bad_example_cluster"
      }
    - |-
      resource "aws_eks_cluster" "bad_example" {
        name = "bad_example_cluster"
        encryption_config {
          resources = ["secrets"]
        }
      }
