cloudformation:
  links:
    - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-eks-cluster-resourcesvpcconfig.html
  good:
    - |-
      Resources:
        EKSCluster:
          Type: AWS::EKS::Cluster
          Properties:
            ResourcesVpcConfig:
              EndpointPublicAccess: false
  bad:
    - |-
      Resources:
        EKSCluster:
          Type: AWS::EKS::Cluster
          Properties:
            ResourcesVpcConfig:
              EndpointPublicAccess: true
terraform:
  links:
    - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster#endpoint_public_access
  good:
    - |-
      resource "aws_eks_cluster" "good_example" {
        name = "good_example_cluster"
        vpc_config {
          endpoint_public_access = false
        }
      }
  bad:
    - |-
      resource "aws_eks_cluster" "bad_example" {
        name = "bad_example_cluster"
        vpc_config {
          endpoint_public_access = true
        }
      }
