terraform:
  good:
    - |-
      resource "azurerm_kubernetes_cluster" "good_example" {
        network_profile {
          network_policy = "calico"
        }
      }
  bad:
    - |-
      resource "azurerm_kubernetes_cluster" "bad_example" {
        network_profile {
        }
      }
