cloudformation:
  good:
    - |-
      Resources:
        GoodExample:
          Type: AWS::WorkSpaces::Workspace
          Properties:
            RootVolumeEncryptionEnabled: true
            UserVolumeEncryptionEnabled: true
  bad:
    - |-
      Resources:
        BadExample:
          Type: AWS::WorkSpaces::Workspace
          Properties:
            RootVolumeEncryptionEnabled: false
            UserVolumeEncryptionEnabled: false
terraform:
  links:
    - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/workspaces_workspace#root_volume_encryption_enabled
  good:
    - |-
      resource "aws_workspaces_workspace" "good_example" {
        root_volume_encryption_enabled = true
        user_volume_encryption_enabled = true
      }
  bad:
    - |-
      resource "aws_workspaces_workspace" "bad_example" {
        # encryption attributes are missing
      }
    - |-
      resource "aws_workspaces_workspace" "bad_example" {
        root_volume_encryption_enabled = false
        user_volume_encryption_enabled = false
      }
