name: Reusable Release
on:
  workflow_call:
    inputs:
      nightly:
        type: boolean
        required: false
        default: false
        description: "Run nightly release"
    secrets:
      TRIVY_CHECKS_DEPLOY_TOKEN:
        required: true
      DOCKERHUB_USER:
        required: true
      DOCKERHUB_TOKEN:
        required: true

env:
  GH_USER: aqua-bot
  AQUA_DOCKERHUB_REPO: aquasec

jobs:
  integration-tests:
    uses: ./.github/workflows/integration-tests.yaml
    permissions:
      contents: read

  release:
    runs-on: ubuntu-2404-2core
    needs: integration-tests
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: go.mod

      - name: Create bundle
        run: make create-bundle

      - name: Setup-oras
        uses: oras-project/setup-oras@22ce207df3b08e061f537244349aac6ae1d214f6 # v1.2.4

      - name: Login to GitHub Packages Container registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ghcr.io
          username: ${{ vars.GHCR_USER || env.GH_USER }}
          password: ${{ secrets.TRIVY_CHECKS_DEPLOY_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set release version
        env:
          NIGHTLY: ${{ inputs.nightly }}
        run: |
          if [ "$NIGHTLY" == "true" ]; then
            BASE_VERSION=$(git describe --tags --abbrev=0)
            BASE_VERSION=${BASE_VERSION#v}
            RELEASE_VERSION="${BASE_VERSION}-nightly.$(date +%Y%m%d)"
          else
            RELEASE_VERSION=${GITHUB_REF#refs/tags/v}
          fi
          echo "Using release version: $RELEASE_VERSION"
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV

      - name: Prepare image tags
        id: prepare-tags
        env:
          NIGHTLY: ${{ inputs.nightly }}
        run: |
          if [ "$NIGHTLY" == "true" ]; then
             tags=("nightly")
           else
             MINOR_VERSION=$(echo $RELEASE_VERSION | cut -d. -f1,2)
             MAJOR_VERSION=$(echo $RELEASE_VERSION | cut -d. -f1)
             tags=("latest" "$RELEASE_VERSION" "$MINOR_VERSION" "$MAJOR_VERSION")
           fi
           echo "tags=${tags[*]}" >> $GITHUB_OUTPUT

      - name: Deploy policy bundle to ghcr.io (for backwards compatibility)
        if: ${{ inputs.nightly != true }}
        env:
          TAGS: ${{ steps.prepare-tags.outputs.tags }}
          REPO_OWNER: ${{ github.event.repository.owner.name }}
        run: |
          tags=($TAGS)
          for tag in ${tags[@]}; do
              echo "Pushing artifact with tag: ${tag}"
              oras push ghcr.io/${REPO_OWNER}/trivy-policies:${tag} \
              --artifact-type application/vnd.cncf.openpolicyagent.config.v1+json \
              --annotation "org.opencontainers.image.source=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" \
              --annotation "org.opencontainers.image.revision=$GITHUB_SHA" \
              --annotation "org.opencontainers.image.version=$RELEASE_VERSION" \
              bundle.tar.gz:application/vnd.cncf.openpolicyagent.layer.v1.tar+gzip
          done

      - name: Deploy checks bundle to registries
        env:
          TAGS: ${{ steps.prepare-tags.outputs.tags }}
          REPOSITORY: ${{ github.repository }}
          REPO_NAME: ${{ github.event.repository.name }}
          DOCKERHUB_REPO: ${{ vars.DOCKERHUB_REPOSITORY || env.AQUA_DOCKERHUB_REPO }}
        run: |
          tags=($TAGS)
          registries=(
            "ghcr.io/${REPOSITORY}"
            "docker.io/${DOCKERHUB_REPO}/${REPO_NAME}"
          )
          for registry in ${registries[@]}; do
            for tag in ${tags[@]}; do
              echo "Pushing artifact to ${registry}:${tag}"
              if oras push ${registry}:${tag} \
              --artifact-type application/vnd.cncf.openpolicyagent.config.v1+json \
              --annotation "org.opencontainers.image.revision=$GITHUB_SHA" \
              --annotation "org.opencontainers.image.version=$RELEASE_VERSION" \
              bundle.tar.gz:application/vnd.cncf.openpolicyagent.layer.v1.tar+gzip; then
                echo "Successfully pushed artifact to ${registry}:${tag}"
              else
                echo "Failed to push artifact to ${registry}:${tag}"
                exit 1
              fi
            done
          done
