name: Test
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
  workflow_dispatch:

permissions: {}

jobs:
  test-go:
    name: Test Go
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - name: Run Go tests
        run: make test

  test-rego:
    name: Test Rego
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - name: Validate Rego syntax
        run: go run ./cmd/opa check lib checks --strict --v0-v1

      - name: Setup Regal
        uses: open-policy-agent/setup-regal@761188c3b435761fa254beca508a44875619648f # v2.0.0
        with:
          version: 0.34.1

      - name: Lint Rego
        run: make lint-rego

      - name: OPA Format
        run: |
          make fmt-rego
          if [ -n "$(git status --porcelain)" ]; then
            echo "Run 'make fmt-rego' and push it"
            exit 1
          fi

      - name: Run Rego tests
        run: make test-rego

      - name: Validate Rego against Trivy schemas
        run: make check-rego-matrix

  test-docs:
    name: Test Docs
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - name: Verify docs are up-to-date
        run: |
          make docs
          if [ -n "$(git status --porcelain)" ]; then
            echo "Run 'make docs' and push it"
            exit 1
          fi

  test-integration:
    uses: ./.github/workflows/integration-tests.yaml
    permissions:
      contents: read
