name: test rego bundle
on:
  pull_request:
  merge_group:

env:
  GO_VERSION: '1.23'

jobs:
  opa-tests:
    name: OPA tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build bundle
        run: make bundle

      - name: Setup OPA
        uses: ./.github/actions/setup-opa

      - name: Check bundle
        run: opa inspect bundle.tar.gz
