cloudformation:
  good:
    - |-
      AWSTemplateFormatVersion: "2010-09-09"

      Description: Good example of ingress rule

      Resources:
        Secret:
          Type: AWS::SecretsManager::Secret
          Properties:
            Description: secret
            KmsKeyId: my-key-id
            Name: blah
            SecretString: don't tell anyone
  bad:
    - |-
      AWSTemplateFormatVersion: "2010-09-09"

      Description: Bad example of secret

      Resources:
        BadSecret:
          Type: AWS::SecretsManager::Secret
          Properties:
            Description: secret
            Name: blah
            SecretString: don't tell anyone
terraform:
  good:
    - |-
      resource "aws_kms_key" "secrets" {
        enable_key_rotation = true
      }

      resource "aws_secretsmanager_secret" "good_example" {
        name       = "lambda_password"
        kms_key_id = aws_kms_key.secrets.arn
      }
  bad:
    - |-
      resource "aws_secretsmanager_secret" "bad_example" {
        name = "lambda_password"
      }
