cloudformation:
  good:
    - |
      AWSTemplateFormatVersion: "2010-09-09T00:00:00Z"
      Description: Good example of ingress rule
      Resources:
        Secret:
          Properties:
            Description: secret
            KmsKeyId: my-key-id
            Name: blah
            SecretString: don't tell anyone
          Type: AWS::SecretsManager::Secret
  bad:
    - |
      AWSTemplateFormatVersion: "2010-09-09T00:00:00Z"
      Description: Bad example of secret
      Resources:
        BadSecret:
          Properties:
            Description: secret
            Name: blah
            SecretString: don't tell anyone
          Type: AWS::SecretsManager::Secret
terraform:
  good:
    - |-
      resource "aws_kms_key" "secrets" {
        enable_key_rotation = true
      }

      resource "aws_secretsmanager_secret" "good_example" {
        name       = "lambda_password"
        kms_key_id = aws_kms_key.secrets.arn
      }
  bad:
    - |-
      resource "aws_secretsmanager_secret" "bad_example" {
        name = "lambda_password"
      }
