cloudformation:
  good:
    - |-
      Resources:
        GoodExample:
          Type: AWS::ECR::Repository
          Properties:
            ImageTagMutability: IMMUTABLE
            RepositoryName: test-repository
  bad:
    - |-
      Resources:
        BadExample:
          Type: AWS::ECR::Repository
          Properties:
            RepositoryName: test-repository
terraform:
  links:
    - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecr_repository
  good:
    - |-
      resource "aws_ecr_repository" "good_example" {
        name                 = "bar"
        image_tag_mutability = "IMMUTABLE"
      }
  bad:
    - |-
      resource "aws_ecr_repository" "bad_example" {
        name                 = "bar"
        image_tag_mutability = "MUTABLE"
      }
