cloudformation:
  good:
    - |-
      Resources:
        GoodExample:
          Type: AWS::ECR::Repository
          Properties:
            EncryptionConfiguration:
              EncryptionType: KMS
              KmsKey: alias/ecr-key
            ImageScanningConfiguration:
              ScanOnPush: false
            ImageTagMutability: IMMUTABLE
            RepositoryName: test-repository
  bad:
    - |-
      Resources:
        BadExample:
          Type: AWS::ECR::Repository
          Properties:
            ImageScanningConfiguration:
              ScanOnPush: false
            RepositoryName: test-repository
terraform:
  good:
    - |-
      resource "aws_ecr_repository" "good_example" {
        name                 = "bar"
        image_tag_mutability = "IMMUTABLE"

        image_scanning_configuration {
          scan_on_push = true
        }
      }
  bad:
    - |-
      resource "aws_ecr_repository" "bad_example" {
        name                 = "bar"
        image_tag_mutability = "MUTABLE"

        image_scanning_configuration {
          scan_on_push = true
        }
      }
