cloudformation:
  good:
    - |-
      Resources:
        GoodExample:
          Type: AWS::ECR::Repository
          Properties:
            RepositoryName: test-repository
            RepositoryPolicyText:
              Statement:
                - Action:
                    - ecr:PutImage
                  Effect: Allow
                  Principal:
                    AWS:
                      - arn:aws:iam::123456789012:user/Alice
                  Sid: AllowPushPull
              Version: "2012-10-17"
  bad:
    - |-
      Resources:
        BadExample:
          Type: AWS::ECR::Repository
          Properties:
            RepositoryName: test-repository
            RepositoryPolicyText:
              Statement:
                - Action:
                    - ecr:PutImage
                  Effect: Allow
                  Principal:
                    AWS:
                      - '*'
                  Sid: AllowPushPull
              Version: "2012-10-17"
terraform:
  links:
    - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecr_repository_policy#policy
  good:
    - |-
      resource "aws_ecr_repository" "example" {
        name = "bar"
      }

      resource "aws_ecr_repository_policy" "example" {
        repository = aws_ecr_repository.example.name
        policy     = <<EOF
       {
           "Version": "2008-10-17",
           "Statement": [
               {
                   "Sid": "new policy",
                   "Effect": "Allow",
                   "Principal": "arn:aws:iam::${data.aws_caller_identity.current.account_id}:root",
                   "Action": [
                       "ecr:SetRepositoryPolicy"
                   ]
               }
           ]
       }
       EOF
      }
  bad:
    - |-
      resource "aws_ecr_repository" "example" {
        name = "bar"
      }

      resource "aws_ecr_repository_policy" "example" {
        repository = aws_ecr_repository.example.name

        policy = <<EOF
       {
           "Version": "2008-10-17",
           "Statement": [
               {
                   "Sid": "new policy",
                   "Effect": "Allow",
                   "Principal": "*",
                   "Action": [
                       "ecr:SetRepositoryPolicy"
                   ]
               }
           ]
       }
       EOF
      }
    - |-
      resource "aws_ecr_repository" "example" {
        name = "bar"
      }

      data "aws_iam_policy_document" "example" {
        version = "2008-10-17"
        statement {
          sid    = "new policy"
          effect = "Allow"
          principals {
            type        = "*"
            identifiers = ["*"]
          }
          actions = [
            "ecr:SetRepositoryPolicy"
          ]
        }
      }

      resource "aws_ecr_repository_policy" "example" {
        repository = aws_ecr_repository.example.name
        policy     = data.aws_iam_policy_document.example.json
      }
