cloudformation:
  good:
    - |-
      Resources:
        GoodExample:
          Type: AWS::ECR::Repository
          Properties:
            EncryptionConfiguration:
              EncryptionType: KMS
              KmsKey: alias/ecr-key
            ImageScanningConfiguration:
              ScanOnPush: false
            ImageTagImmutability: IMMUTABLE
            RepositoryName: test-repository
            RepositoryPolicyText:
              Statement:
                - Action:
                    - ecr:GetDownloadUrlForLayer
                    - ecr:BatchGetImage
                    - ecr:BatchCheckLayerAvailability
                    - ecr:PutImage
                    - ecr:InitiateLayerUpload
                    - ecr:UploadLayerPart
                    - ecr:CompleteLayerUpload
                  Effect: Allow
                  Principal:
                    AWS:
                      - arn:aws:iam::123456789012:user/Alice
                  Sid: AllowPushPull
              Version: "2012-10-17"
  bad:
    - |-
      Resources:
        BadExample:
          Type: AWS::ECR::Repository
          Properties:
            ImageScanningConfiguration:
              ScanOnPush: false
            RepositoryName: test-repository
            RepositoryPolicyText:
              Statement:
                - Action:
                    - ecr:GetDownloadUrlForLayer
                    - ecr:BatchGetImage
                    - ecr:BatchCheckLayerAvailability
                    - ecr:PutImage
                    - ecr:InitiateLayerUpload
                    - ecr:UploadLayerPart
                    - ecr:CompleteLayerUpload
                  Effect: Allow
                  Principal:
                    AWS:
                      - '*'
                  Sid: AllowPushPull
              Version: "2012-10-17"
terraform:
  good:
    - |-
      resource "aws_ecr_repository" "foo" {
        name = "bar"
      }

      resource "aws_ecr_repository_policy" "foopolicy" {
        repository = aws_ecr_repository.foo.name

        policy = <<EOF
       {
           "Version": "2008-10-17",
           "Statement": [
               {
                   "Sid": "new policy",
                   "Effect": "Allow",
                   "Principal": "arn:aws:iam::${data.aws_caller_identity.current.account_id}:root",
                   "Action": [
                       "ecr:GetDownloadUrlForLayer",
                       "ecr:BatchGetImage",
                       "ecr:BatchCheckLayerAvailability",
                       "ecr:PutImage",
                       "ecr:InitiateLayerUpload",
                       "ecr:UploadLayerPart",
                       "ecr:CompleteLayerUpload",
                       "ecr:DescribeRepositories",
                       "ecr:GetRepositoryPolicy",
                       "ecr:ListImages",
                       "ecr:DeleteRepository",
                       "ecr:BatchDeleteImage",
                       "ecr:SetRepositoryPolicy",
                       "ecr:DeleteRepositoryPolicy"
                   ]
               }
           ]
       }
       EOF
      }
  bad:
    - |-
      resource "aws_ecr_repository" "foo" {
        name = "bar"
      }

      resource "aws_ecr_repository_policy" "foopolicy" {
        repository = aws_ecr_repository.foo.name

        policy = <<EOF
       {
           "Version": "2008-10-17",
           "Statement": [
               {
                   "Sid": "new policy",
                   "Effect": "Allow",
                   "Principal": "*",
                   "Action": [
                       "ecr:GetDownloadUrlForLayer",
                       "ecr:BatchGetImage",
                       "ecr:BatchCheckLayerAvailability",
                       "ecr:PutImage",
                       "ecr:InitiateLayerUpload",
                       "ecr:UploadLayerPart",
                       "ecr:CompleteLayerUpload",
                       "ecr:DescribeRepositories",
                       "ecr:GetRepositoryPolicy",
                       "ecr:ListImages",
                       "ecr:DeleteRepository",
                       "ecr:BatchDeleteImage",
                       "ecr:SetRepositoryPolicy",
                       "ecr:DeleteRepositoryPolicy"
                   ]
               }
           ]
       }
       EOF
      }
