cloudformation:
  good:
    - |-
      Resources:
        GoodExample:
          Type: AWS::ECR::Repository
          Properties:
            EncryptionConfiguration:
              EncryptionType: KMS
              KmsKey: alias/ecr-key
            ImageScanningConfiguration:
              ScanOnPush: false
            ImageTagImmutability: IMMUTABLE
            RepositoryName: test-repository
  bad:
    - |-
      Resources:
        BadExample:
          Type: AWS::ECR::Repository
          Properties:
            ImageScanningConfiguration:
              ScanOnPush: false
            RepositoryName: test-repository
terraform:
  good:
    - |-
      resource "aws_kms_key" "ecr_kms" {
        enable_key_rotation = true
      }

      resource "aws_ecr_repository" "good_example" {
        name                 = "bar"
        image_tag_mutability = "MUTABLE"

        image_scanning_configuration {
          scan_on_push = true
        }

        encryption_configuration {
          encryption_type = "KMS"
          kms_key         = aws_kms_key.ecr_kms.key_id
        }
      }
  bad:
    - |-
      resource "aws_ecr_repository" "bad_example" {
        name                 = "bar"
        image_tag_mutability = "MUTABLE"

        image_scanning_configuration {
          scan_on_push = true
        }
      }
