cloudformation:
  links:
    - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html#cfn-ecr-repository-encryptionconfiguration
  good:
    - |-
      Resources:
        GoodExample:
          Type: AWS::ECR::Repository
          Properties:
            EncryptionConfiguration:
              EncryptionType: KMS
              KmsKey: alias/ecr-key
            RepositoryName: test-repository
  bad:
    - |-
      Resources:
        BadExample:
          Type: AWS::ECR::Repository
          Properties:
            RepositoryName: test-repository
terraform:
  links:
    - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecr_repository#encryption_configuration
  good:
    - |-
      resource "aws_kms_key" "ecr_kms" {
        enable_key_rotation = true
      }

      resource "aws_ecr_repository" "good_example" {
        name = "bar"
        encryption_configuration {
          encryption_type = "KMS"
          kms_key         = aws_kms_key.ecr_kms.key_id
        }
      }
  bad:
    - |-
      resource "aws_ecr_repository" "bad_example" {
        name = "bar"
      }
    - |-
      resource "aws_ecr_repository" "bad_example" {
        name = "bar"
        encryption_configuration {
          encryption_type = "KMS"
        }
      }
